(() => {
  const CHAT_KEY='dafatii:chatState:v1';
  const PRO_KEY='dafatii:chatProState:v1';
  const MAX_IMAGE=1200*1024, MAX_VIDEO=2200*1024, MAX_DOC=1000*1024, MAX_VOICE=900*1024;
  const SUBS=['Private chats','Groups','Unknown messages'];
  const now=()=>Date.now();
  const uid=p=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;
  const esc=v=>escapeHtml(v??'');
  let voiceRecorder=null,voiceStream=null,voiceChunks=[],voiceConversationId='';
  const ui={filter:'all',query:'',info:false,search:false,searchQuery:'',menuMessage:'',replyTo:'',editing:'',attach:false,emoji:false,sticker:false,mobileThread:false};

  function read(key,fallback){return window.DafatiiData.readJSON(key,fallback);}
  function write(key,value){try{window.DafatiiData.writeJSON(key,value);return true;}catch{showToast('Browser storage is full. Remove large chat media and try again.');return false;}}
  function clone(v){return JSON.parse(JSON.stringify(v));}
  function chatState(){
    const raw=read(CHAT_KEY,{conversations:[],selected:{private:'',group:'',unknown:''},reported:[],blocked:[]});
    const state={conversations:Array.isArray(raw.conversations)?raw.conversations:[],selected:{private:'',group:'',unknown:'',...(raw.selected||{})},reported:Array.isArray(raw.reported)?raw.reported:[],blocked:Array.isArray(raw.blocked)?raw.blocked:[]};
    if(!state.conversations.some(c=>c.id==='saved-messages')) state.conversations.unshift({id:'saved-messages',kind:'private',name:'Saved Messages',avatar:'★',status:'your private cloud-style scratchpad',messages:[]});
    state.conversations.forEach(c=>{c.messages=Array.isArray(c.messages)?c.messages:[];c.messages.forEach(m=>{m.reactions=m.reactions||{};m.status=m.status||'read';});});
    return state;
  }
  function saveChat(state){return write(CHAT_KEY,state);}
  function proState(){
    const raw=read(PRO_KEY,{});
    return {meta:raw.meta&&typeof raw.meta==='object'?raw.meta:{},drafts:raw.drafts&&typeof raw.drafts==='object'?raw.drafts:{},starred:raw.starred&&typeof raw.starred==='object'?raw.starred:{},scheduled:Array.isArray(raw.scheduled)?raw.scheduled:[],chatSettings:raw.chatSettings&&typeof raw.chatSettings==='object'?raw.chatSettings:{}};
  }
  function savePro(state){return write(PRO_KEY,state);}
  function metaFor(pro,id){return pro.meta[id]||(pro.meta[id]={pinned:false,archived:false,muted:false,unread:false});}
  function kindFromSub(sub){const s=String(sub||'').toLowerCase();return s==='groups'?'group':s==='unknown messages'?'unknown':'private';}
  function subLabel(kind){return kind==='group'?'Groups':kind==='unknown'?'Unknown messages':'Private chats';}
  function currentSub(parts){return decodeURIComponent(parts.slice(1).join('/'))||SUBS[0];}
  function fmtTime(t){try{return new Date(t).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});}catch{return '';}}
  function fmtDay(t){const d=new Date(t),today=new Date(),y=new Date(Date.now()-86400000);if(d.toDateString()===today.toDateString())return 'Today';if(d.toDateString()===y.toDateString())return 'Yesterday';return d.toLocaleDateString([],{month:'short',day:'numeric'});}
  function rel(t){const m=Math.max(0,Math.floor((now()-Number(t||now()))/60000));if(m<1)return 'now';if(m<60)return `${m}m`;const h=Math.floor(m/60);if(h<24)return `${h}h`;return `${Math.floor(h/24)}d`;}
  function lastMessage(c){return c.messages[c.messages.length-1]||null;}
  function preview(m){if(!m)return 'No messages yet';if(m.deleted)return 'Message deleted';if(m.type==='image')return '📷 Photo';if(m.type==='video')return '🎥 Video';if(m.type==='voice')return '🎙 Voice message';if(m.type==='file')return `📎 ${m.name||'Document'}`;if(m.type==='sticker'||m.type==='custom-sticker')return '✨ Sticker';if(m.type==='gif'||m.type==='gif-maker')return 'GIF';if(m.type==='contact')return `👤 ${m.contactName||'Contact'}`;if(m.type==='location')return '📍 Location';if(m.type==='poll')return `📊 ${m.question||'Poll'}`;return m.text||'Message';}
  function ensureSelected(state,kind,conversations){let id=state.selected[kind];if(!conversations.some(c=>c.id===id))id=conversations[0]?.id||'';state.selected[kind]=id;return id;}
  function findConversation(state,id){return state.conversations.find(c=>c.id===id);}

  const previousWorkspaceContent=workspaceContent;
  workspaceContent=function(page,parts,title){if(page==='chat')return proChatView(parts);return previousWorkspaceContent(page,parts,title);};
  const previousWorkspace=workspace;
  workspace=function(current){cancelVoiceIfLeaving(current);previousWorkspace(current);if(current.split('/')[0]==='chat')bindProChat();};

  function proChatView(parts){
    const kind=kindFromSub(currentSub(parts));
    const state=chatState(),pro=proState();
    processScheduled(state,pro);
    let conversations=state.conversations.filter(c=>c.kind===kind);
    const selectedId=ensureSelected(state,kind,conversations);
    const selected=findConversation(state,selectedId)||conversations[0]||null;
    conversations=sortConversations(conversations,pro);
    return `<section class="chatpro-page ${ui.mobileThread&&selected?'mobile-thread':''}" data-kind="${kind}" data-selected="${esc(selected?.id||'')}">
      <div class="chatpro-shell">
        <aside class="chatpro-rail">
          ${railHeader(kind)}
          ${statusStrip(kind,state)}
          ${filterBar()}
          <div class="chatpro-list" id="chatpro-list">${conversationList(conversations,selectedId,pro)}</div>
        </aside>
        <main class="chatpro-thread">${selected?threadView(selected,state,pro):emptyThread(kind)}</main>
        ${selected&&ui.info?infoPanel(selected,state,pro):''}
      </div>
      <div id="chatpro-layer"></div>
    </section>`;
  }
  function sortConversations(conversations,pro){return [...conversations].sort((a,b)=>{const ma=metaFor(pro,a.id),mb=metaFor(pro,b.id);if(ma.pinned!==mb.pinned)return ma.pinned?-1:1;return Number(lastMessage(b)?.at||0)-Number(lastMessage(a)?.at||0);});}
  function railHeader(kind){return `<div class="chatpro-rail-head"><div><div class="eyebrow">Dafatii Chat</div><h1>${esc(subLabel(kind))}</h1></div><div class="chatpro-rail-actions"><button id="chatpro-new" title="New chat">＋</button><button id="chatpro-rail-menu" title="Chat menu">⋮</button></div></div><label class="chatpro-search"><span>⌕</span><input id="chatpro-search" value="${esc(ui.query)}" placeholder="Search chats and people"><kbd>⌘K</kbd></label>`;}
  function statusStrip(kind,state){if(kind==='unknown')return `<div class="chatpro-anon-banner"><strong>◌ Anonymous inbox</strong><span>Your profile identity stays hidden in this section. Report and block controls remain available.</span></div>`;const people=state.conversations.filter(c=>c.kind===kind).slice(0,6);return `<div class="chatpro-status-strip"><button class="chatpro-status-add"><span>＋</span><small>New</small></button>${people.map((c,i)=>`<button class="chatpro-status"><span class="ring ${i<3?'active':''}"><b>${esc(c.avatar||c.name?.[0]||'?')}</b></span><small>${esc((c.name||'').split(' ')[0])}</small></button>`).join('')}</div>`;}
  function filterBar(){return `<div class="chatpro-filters">${[['all','All'],['unread','Unread'],['starred','Starred'],['archived','Archived']].map(([id,label])=>`<button data-filter="${id}" class="${ui.filter===id?'active':''}">${label}</button>`).join('')}</div>`;}
  function conversationList(conversations,selectedId,pro){
    const q=ui.query.trim().toLowerCase();
    const filtered=conversations.filter(c=>{const m=metaFor(pro,c.id);if(ui.filter==='archived'&&!m.archived)return false;if(ui.filter!=='archived'&&m.archived)return false;if(ui.filter==='unread'&&!m.unread&&!c.unread)return false;if(ui.filter==='starred'&&!Object.values(pro.starred[c.id]||{}).some(Boolean))return false;if(q&&!`${c.name} ${preview(lastMessage(c))}`.toLowerCase().includes(q))return false;return true;});
    if(!filtered.length)return `<div class="chatpro-empty-list"><div>⌁</div><strong>No chats match</strong><span>Try another filter or search.</span></div>`;
    return filtered.map(c=>conversationRow(c,c.id===selectedId,pro)).join('');
  }
  function conversationRow(c,active,pro){const m=lastMessage(c),meta=metaFor(pro,c.id),draft=pro.drafts[c.id],unread=Number(c.unread||0)+(meta.unread?1:0);return `<article class="chatpro-conversation ${active?'active':''}" data-open-chat="${esc(c.id)}"><button class="chatpro-conv-main"><span class="chatpro-avatar ${c.status==='online'?'online':''}">${esc(c.avatar||c.name?.[0]||'?')}</span><span class="chatpro-conv-copy"><span class="chatpro-conv-title"><strong>${esc(c.name)}</strong>${meta.muted?'<i title="Muted">⌁</i>':''}${meta.pinned?'<i title="Pinned">⌖</i>':''}</span><span class="chatpro-preview ${draft?'draft':''}">${draft?`Draft: ${esc(draft)}`:esc(preview(m))}</span></span><span class="chatpro-conv-meta"><time>${m?rel(m.at):''}</time>${unread?`<b>${unread>99?'99+':unread}</b>`:''}</span></button><button class="chatpro-conv-more" data-conv-more="${esc(c.id)}" aria-label="Conversation options">⋮</button></article>`;}

  function threadView(c,state,pro){const blocked=state.blocked.includes(c.id),settings=pro.chatSettings[c.id]||{},pinned=settings.pinnedMessageId?c.messages.find(m=>m.id===settings.pinnedMessageId):null;return `${threadHeader(c,state,pro)}${pinned?`<button class="chatpro-pinned" id="chatpro-pinned"><span>⌖</span><div><strong>Pinned message</strong><small>${esc(preview(pinned))}</small></div><b>›</b></button>`:''}${ui.search?threadSearch(c):''}<div class="chatpro-messages" id="chatpro-messages">${messageTimeline(c,pro)}</div>${blocked?blockedBar(c):composer(c,pro)}`;}
  function threadHeader(c,state,pro){const blocked=state.blocked.includes(c.id);return `<div class="chatpro-thread-head"><button class="chatpro-mobile-back" id="chatpro-mobile-back">‹</button><button class="chatpro-person" id="chatpro-info"><span class="chatpro-avatar large ${c.status==='online'?'online':''}">${esc(c.avatar||c.name?.[0]||'?')}</span><span><strong>${esc(c.name)}</strong><small>${esc(blocked?'blocked':c.status||c.topic||'last seen recently')}</small></span></button><div class="chatpro-head-actions"><button id="chatpro-call" title="Voice call">☎</button><button id="chatpro-video-call" title="Video call">▣</button><button id="chatpro-thread-search" title="Search in conversation">⌕</button>${c.kind==='unknown'?`<button id="chatpro-report" class="danger-text">Report</button>`:''}<button id="chatpro-info-button" title="Chat info">ⓘ</button></div></div>`;}
  function threadSearch(c){const q=ui.searchQuery.trim().toLowerCase(),matches=q?c.messages.filter(m=>String(m.text||m.name||m.question||'').toLowerCase().includes(q)).length:0;return `<div class="chatpro-thread-search"><span>⌕</span><input id="chatpro-thread-search-input" value="${esc(ui.searchQuery)}" placeholder="Search messages"><small>${q?`${matches} found`:''}</small><button id="chatpro-search-close">×</button></div>`;}
  function messageTimeline(c,pro){if(!c.messages.length)return `<div class="chatpro-empty-thread"><div>✦</div><h2>No messages yet</h2><p>Start the conversation or share a study file.</p></div>`;let lastDay='';return c.messages.map(m=>{const day=fmtDay(m.at);const marker=day!==lastDay?`<div class="chatpro-day"><span>${esc(day)}</span></div>`:'';lastDay=day;return marker+messageRow(m,c,pro);}).join('');}
  function messageRow(m,c,pro){const reply=m.replyTo?c.messages.find(x=>x.id===m.replyTo):null,starred=Boolean(pro.starred[c.id]?.[m.id]);return `<div class="chatpro-msg-row ${m.mine?'mine':'theirs'} ${ui.menuMessage===m.id?'menu-open':''}" data-message-id="${esc(m.id)}"><div class="chatpro-msg-wrap">${c.kind==='group'&&!m.mine?`<small class="chatpro-sender">${esc(m.sender||c.name)}</small>`:''}<div class="chatpro-bubble ${m.type&&m.type!=='text'?'media':''} ${m.deleted?'deleted':''}">${m.forwarded?'<div class="chatpro-forwarded">↪ Forwarded</div>':''}${reply?`<button class="chatpro-reply-quote" data-jump-message="${esc(reply.id)}"><strong>${esc(reply.mine?'You':reply.sender||c.name)}</strong><span>${esc(preview(reply))}</span></button>`:''}${renderMessage(m)}<div class="chatpro-msg-foot">${m.edited?'<span>edited</span>':''}${starred?'<span>★</span>':''}<time>${esc(fmtTime(m.at))}</time>${m.mine?`<span class="chatpro-status ${m.status==='read'?'read':''}">✓✓</span>`:''}</div></div>${renderReactions(m)}<div class="chatpro-hover-actions"><button data-quick-react="❤️">♡</button><button data-message-reply>↩</button><button data-message-more>⋮</button></div>${ui.menuMessage===m.id?messageMenu(m,c,starred):''}</div></div>`;}
  function renderMessage(m){if(m.deleted)return `<div class="chatpro-deleted">⊘ This message was deleted</div>`;if(m.type==='image')return `<img class="chatpro-image" src="${esc(m.data)}" alt="Shared image">${m.caption?`<p class="chatpro-caption">${esc(m.caption)}</p>`:''}`;if(m.type==='video')return `<video class="chatpro-video" src="${esc(m.data)}" controls playsinline></video>${m.caption?`<p class="chatpro-caption">${esc(m.caption)}</p>`:''}`;if(m.type==='voice')return `<div class="chatpro-voice"><button>▶</button><audio src="${esc(m.data)}" controls preload="metadata"></audio><span>🎙</span></div>`;if(m.type==='file')return `<a class="chatpro-file" href="${esc(m.data)}" download="${esc(m.name||'document')}"><span>▤</span><div><strong>${esc(m.name||'Document')}</strong><small>${esc(m.sizeLabel||'File')}</small></div><b>⇩</b></a>`;if(m.type==='sticker')return `<div class="chatpro-sticker">${esc(m.text||'✨')}</div>`;if(m.type==='custom-sticker')return `<div class="chatpro-custom-sticker"><span>${esc(m.emoji||'✨')}</span><strong>${esc(m.text||'Study mode')}</strong></div>`;if(m.type==='gif')return `<img class="chatpro-gif" src="${esc(m.data)}" alt="GIF">`;if(m.type==='gif-maker')return `<div class="chatpro-made-gif"><span>${esc(m.frame1||'FOCUS')}</span><span>${esc(m.frame2||'DONE')}</span></div>`;if(m.type==='contact')return `<div class="chatpro-contact"><span>👤</span><div><strong>${esc(m.contactName||'Contact')}</strong><small>${esc(m.contactValue||'')}</small></div><button data-contact-save>Save</button></div>`;if(m.type==='location')return `<a class="chatpro-location" href="https://www.openstreetmap.org/?mlat=${Number(m.lat)}&mlon=${Number(m.lon)}#map=15/${Number(m.lat)}/${Number(m.lon)}" target="_blank" rel="noopener noreferrer"><span>📍</span><div><strong>Shared location</strong><small>${Number(m.lat).toFixed(4)}, ${Number(m.lon).toFixed(4)}</small></div></a>`;if(m.type==='poll')return pollView(m);return `<div class="chatpro-text">${linkify(esc(m.text||''))}</div>`;}
  function linkify(text){return text.replace(/(https?:\/\/[^\s<]+)/g,'<a href="$1" target="_blank" rel="noopener noreferrer">$1</a>');}
  function pollView(m){const total=(m.options||[]).reduce((s,o)=>s+Number(o.votes||0),0)||1;return `<div class="chatpro-poll"><strong>📊 ${esc(m.question||'Poll')}</strong>${(m.options||[]).map((o,i)=>`<button data-poll-vote="${i}" class="${o.voted?'voted':''}"><span>${esc(o.text)}</span><b>${Math.round((Number(o.votes||0)/total)*100)}%</b><i style="--poll:${Math.round((Number(o.votes||0)/total)*100)}%"></i></button>`).join('')}</div>`;}
  function renderReactions(m){const r=Object.entries(m.reactions||{}).filter(([,n])=>n>0);return r.length?`<div class="chatpro-reactions">${r.map(([e,n])=>`<button data-reaction="${esc(e)}">${esc(e)} ${n}</button>`).join('')}</div>`:'';}
  function messageMenu(m,c,starred){return `<div class="chatpro-msg-menu"><button data-message-action="reply">↩ Reply</button><button data-message-action="forward">↪ Forward</button><button data-message-action="star">${starred?'☆ Unstar':'★ Star'}</button><button data-message-action="pin">⌖ Pin</button>${m.type==='text'&&!m.deleted?'<button data-message-action="copy">⧉ Copy</button>':''}${m.mine&&m.type==='text'&&!m.deleted?'<button data-message-action="edit">✎ Edit</button>':''}<button data-message-action="delete" class="danger-text">⌫ Delete</button></div>`;}
  function blockedBar(c){return `<div class="chatpro-blocked"><span>⊘ You blocked this anonymous conversation.</span><button id="chatpro-unblock">Unblock</button></div>`;}

  function composer(c,pro){const reply=ui.replyTo?c.messages.find(m=>m.id===ui.replyTo):null,editing=ui.editing?c.messages.find(m=>m.id===ui.editing):null,draft=editing?.text??pro.drafts[c.id]??'';return `<div class="chatpro-composer-zone">${reply||editing?`<div class="chatpro-compose-context"><span>${editing?'✎':'↩'}</span><div><strong>${editing?'Edit message':`Reply to ${reply?.mine?'yourself':reply?.sender||c.name}`}</strong><small>${esc(editing?.text||preview(reply))}</small></div><button id="chatpro-context-close">×</button></div>`:''}${ui.attach?attachmentMenu(c):''}${ui.emoji?emojiPicker():''}${ui.sticker?stickerPanel():''}<div class="chatpro-composer"><button id="chatpro-attach" title="Attach">＋</button><button id="chatpro-emoji" title="Emoji">☺</button><textarea id="chatpro-input" rows="1" maxlength="5000" placeholder="Message ${esc(c.name)}…">${esc(draft)}</textarea><button id="chatpro-voice" title="Voice message">🎙</button><button id="chatpro-schedule" title="Schedule message">◷</button><button id="chatpro-send" class="send" title="Send">➤</button></div><input id="chatpro-media-file" type="file" accept="image/*,video/*" hidden><input id="chatpro-doc-file" type="file" accept=".pdf,.txt,.md,.doc,.docx,.ppt,.pptx,.xls,.xlsx,.zip" hidden></div>`;}
  function attachmentMenu(c){return `<div class="chatpro-attach-menu"><button data-attach-kind="media"><span>▧</span><b>Photos & videos</b></button><button data-attach-kind="document"><span>▤</span><b>Document</b></button><button data-attach-kind="contact"><span>👤</span><b>Contact</b></button><button data-attach-kind="location"><span>📍</span><b>Location</b></button>${c.kind==='group'?'<button data-attach-kind="poll"><span>📊</span><b>Poll</b></button>':''}<button data-attach-kind="sticker"><span>✨</span><b>Sticker / GIF</b></button></div>`;}
  function emojiPicker(){const e=['😀','😂','🥹','😍','😭','😤','🤯','😴','🫡','🤝','❤️','🔥','💯','✅','⚡','🎓','📚','🧠','☕','🚀','🧪','📐','🎯','🙌','👀','✨','🥳','🤍','👍','👎'];return `<div class="chatpro-emoji-picker"><div class="chatpro-picker-head"><strong>Emoji</strong><button data-close-picker>×</button></div><div>${e.map(x=>`<button data-insert-emoji="${x}">${x}</button>`).join('')}</div></div>`;}
  function stickerPanel(){const s=['📚','🧠','🔥','😭','😂','💯','🫡','⚡','☕','🎓','✅','🤝','😴','🚀'];return `<div class="chatpro-sticker-panel"><div class="chatpro-picker-head"><strong>Stickers & GIFs</strong><button data-close-picker>×</button></div><div class="chatpro-provider"><button data-provider="https://giphy.com/search/study">GIPHY ↗</button><button data-provider="https://tenor.com/search/study-gifs">Tenor ↗</button></div><div class="chatpro-sticker-grid">${s.map(x=>`<button data-send-sticker="${x}">${x}</button>`).join('')}</div><div class="chatpro-gif-entry"><input id="chatpro-gif-url" placeholder="Paste direct GIF URL"><button id="chatpro-gif-send">Send GIF</button></div><button class="chatpro-make" id="chatpro-make-sticker">＋ Make sticker</button></div>`;}

  function infoPanel(c,state,pro){const meta=metaFor(pro,c.id),starred=Object.keys(pro.starred[c.id]||{}).filter(id=>pro.starred[c.id][id]),media=c.messages.filter(m=>['image','video','gif'].includes(m.type)).slice(-6);const participants=c.kind==='group'?(c.participants||['You','Lina','Yousef','Noor','Omar']):[];return `<aside class="chatpro-info"><div class="chatpro-info-head"><strong>Chat info</strong><button id="chatpro-info-close">×</button></div><div class="chatpro-profile"><span class="chatpro-avatar xlarge">${esc(c.avatar||c.name?.[0]||'?')}</span><h2>${esc(c.name)}</h2><p>${esc(c.status||c.topic||'')}</p></div><div class="chatpro-info-actions"><button data-info-action="mute"><span>${meta.muted?'🔔':'🔕'}</span><small>${meta.muted?'Unmute':'Mute'}</small></button><button data-info-action="pin"><span>⌖</span><small>${meta.pinned?'Unpin':'Pin'}</small></button><button data-info-action="archive"><span>▣</span><small>${meta.archived?'Unarchive':'Archive'}</small></button></div>${media.length?`<section><header><strong>Media</strong><button data-info-action="media">${media.length} items</button></header><div class="chatpro-media-grid">${media.map(m=>m.type==='video'?`<div class="video-thumb">▶</div>`:`<img src="${esc(m.data)}" alt="Media">`).join('')}</div></section>`:''}<section><header><strong>Starred messages</strong><span>${starred.length}</span></header>${starred.length?`<div class="chatpro-starred-list">${starred.slice(-5).map(id=>{const m=c.messages.find(x=>x.id===id);return m?`<button data-jump-message="${esc(id)}">${esc(preview(m))}</button>`:'';}).join('')}</div>`:'<p class="chatpro-info-muted">No starred messages.</p>'}</section>${c.kind==='group'?`<section><header><strong>${participants.length} participants</strong><button id="chatpro-add-member">＋ Add</button></header><div class="chatpro-participants">${participants.map((p,i)=>`<div><span>${esc(p[0])}</span><strong>${esc(p)}</strong>${i===0?'<small>admin</small>':''}</div>`).join('')}</div></section>`:''}<section class="chatpro-danger-zone">${c.kind==='unknown'?`<button data-info-action="block">${state.blocked.includes(c.id)?'Unblock':'Block'} anonymous sender</button>`:''}<button data-info-action="clear">Clear chat</button><button data-info-action="delete">Delete conversation</button></section></aside>`;}
  function emptyThread(kind){return `<div class="chatpro-empty-thread big"><div>✦</div><h2>${kind==='group'?'Pick a group':kind==='unknown'?'Open an anonymous message':'Choose a conversation'}</h2><p>Messages, media, documents, reactions and study conversations will appear here.</p></div>`;}

  function bindProChat(){
    const page=document.querySelector('.chatpro-page');if(!page)return;
    const kind=page.dataset.kind;const selectedId=page.dataset.selected;let state=chatState(),pro=proState(),c=findConversation(state,selectedId);
    document.getElementById('chatpro-search')?.addEventListener('input',e=>{ui.query=e.target.value;softRerender();});
    document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{ui.filter=b.dataset.filter;render();});
    document.querySelectorAll('[data-open-chat]').forEach(row=>row.addEventListener('click',e=>{if(e.target.closest('[data-conv-more]'))return;state.selected[kind]=row.dataset.openChat;const meta=metaFor(pro,row.dataset.openChat);meta.unread=false;const conv=findConversation(state,row.dataset.openChat);if(conv)conv.unread=0;saveChat(state);savePro(pro);resetTransient();ui.mobileThread=true;render();}));
    document.querySelectorAll('[data-conv-more]').forEach(b=>b.onclick=e=>{e.stopPropagation();openConversationMenu(b.dataset.convMore,state,pro);});
    document.getElementById('chatpro-new')?.addEventListener('click',()=>openNewChatSheet(kind,state));
    document.getElementById('chatpro-rail-menu')?.addEventListener('click',()=>openRailMenu(kind));
    if(!c)return;
    bindThread(c,state,pro);
  }
  function softRerender(){const list=document.getElementById('chatpro-list');if(!list)return;const page=document.querySelector('.chatpro-page'),kind=page.dataset.kind,state=chatState(),pro=proState(),conversations=sortConversations(state.conversations.filter(c=>c.kind===kind),pro);list.innerHTML=conversationList(conversations,page.dataset.selected,pro);document.querySelectorAll('[data-open-chat]').forEach(row=>row.addEventListener('click',e=>{if(e.target.closest('[data-conv-more]'))return;state.selected[kind]=row.dataset.openChat;const meta=metaFor(pro,row.dataset.openChat);meta.unread=false;const conv=findConversation(state,row.dataset.openChat);if(conv)conv.unread=0;saveChat(state);savePro(pro);resetTransient();ui.mobileThread=true;render();}));document.querySelectorAll('[data-conv-more]').forEach(b=>b.onclick=e=>{e.stopPropagation();openConversationMenu(b.dataset.convMore,state,pro);});}
  function resetTransient(){ui.info=false;ui.search=false;ui.searchQuery='';ui.menuMessage='';ui.replyTo='';ui.editing='';ui.attach=false;ui.emoji=false;ui.sticker=false;}

  function bindThread(c,state,pro){
    document.getElementById('chatpro-mobile-back')?.addEventListener('click',()=>{ui.mobileThread=false;render();});
    document.getElementById('chatpro-info')?.addEventListener('click',()=>{ui.info=!ui.info;render();});
    document.getElementById('chatpro-info-button')?.addEventListener('click',()=>{ui.info=!ui.info;render();});
    document.getElementById('chatpro-info-close')?.addEventListener('click',()=>{ui.info=false;render();});
    document.getElementById('chatpro-thread-search')?.addEventListener('click',()=>{ui.search=!ui.search;render();});
    document.getElementById('chatpro-search-close')?.addEventListener('click',()=>{ui.search=false;ui.searchQuery='';render();});
    document.getElementById('chatpro-thread-search-input')?.addEventListener('input',e=>{ui.searchQuery=e.target.value;const q=ui.searchQuery.toLowerCase();document.querySelectorAll('.chatpro-msg-row').forEach(r=>{r.classList.toggle('search-hit',q&&r.textContent.toLowerCase().includes(q));});});
    document.getElementById('chatpro-call')?.addEventListener('click',()=>openCallSheet(c,'voice'));
    document.getElementById('chatpro-video-call')?.addEventListener('click',()=>openCallSheet(c,'video'));
    document.getElementById('chatpro-report')?.addEventListener('click',()=>{if(!state.reported.includes(c.id))state.reported.push(c.id);saveChat(state);showToast('Anonymous conversation reported');});
    document.getElementById('chatpro-unblock')?.addEventListener('click',()=>toggleBlock(c,state));
    document.getElementById('chatpro-pinned')?.addEventListener('click',()=>{const id=(pro.chatSettings[c.id]||{}).pinnedMessageId;scrollToMessage(id);});
    bindMessages(c,state,pro);bindComposer(c,state,pro);bindInfo(c,state,pro);
    requestAnimationFrame(()=>{const box=document.getElementById('chatpro-messages');if(box)box.scrollTop=box.scrollHeight;});
  }
  function bindMessages(c,state,pro){
    document.querySelectorAll('[data-message-more]').forEach(b=>b.onclick=e=>{e.stopPropagation();const id=b.closest('[data-message-id]').dataset.messageId;ui.menuMessage=ui.menuMessage===id?'':id;render();});
    document.querySelectorAll('[data-message-reply]').forEach(b=>b.onclick=()=>{ui.replyTo=b.closest('[data-message-id]').dataset.messageId;ui.editing='';ui.menuMessage='';render();});
    document.querySelectorAll('[data-quick-react],[data-reaction]').forEach(b=>b.onclick=()=>{const row=b.closest('[data-message-id]'),m=c.messages.find(x=>x.id===row.dataset.messageId),emoji=b.dataset.quickReact||b.dataset.reaction;if(!m)return;m.reactions=m.reactions||{};m.reactions[emoji]=(m.reactions[emoji]||0)+1;saveChat(state);render();});
    document.querySelectorAll('[data-message-action]').forEach(b=>b.onclick=()=>handleMessageAction(b.dataset.messageAction,b.closest('[data-message-id]').dataset.messageId,c,state,pro));
    document.querySelectorAll('[data-jump-message]').forEach(b=>b.onclick=()=>scrollToMessage(b.dataset.jumpMessage));
    document.querySelectorAll('[data-poll-vote]').forEach(b=>b.onclick=()=>{const row=b.closest('[data-message-id]'),m=c.messages.find(x=>x.id===row.dataset.messageId),idx=Number(b.dataset.pollVote);if(!m?.options?.[idx])return;m.options.forEach(o=>o.voted=false);m.options[idx].votes=(m.options[idx].votes||0)+1;m.options[idx].voted=true;saveChat(state);render();});
    document.querySelectorAll('[data-contact-save]').forEach(b=>b.onclick=()=>showToast('Contact saved in this browser prototype'));
  }
  function handleMessageAction(action,id,c,state,pro){const m=c.messages.find(x=>x.id===id);if(!m)return;ui.menuMessage='';if(action==='reply'){ui.replyTo=id;ui.editing='';render();return;}if(action==='forward'){openForwardSheet(m,state);return;}if(action==='star'){pro.starred[c.id]=pro.starred[c.id]||{};pro.starred[c.id][id]=!pro.starred[c.id][id];savePro(pro);render();return;}if(action==='pin'){pro.chatSettings[c.id]=pro.chatSettings[c.id]||{};pro.chatSettings[c.id].pinnedMessageId=id;savePro(pro);render();return;}if(action==='copy'){navigator.clipboard?.writeText(m.text||'').then(()=>showToast('Message copied')).catch(()=>showToast('Copy unavailable'));return;}if(action==='edit'){ui.editing=id;ui.replyTo='';render();return;}if(action==='delete'){openDeleteMessageSheet(m,c,state);}}
  function scrollToMessage(id){if(!id)return;const row=document.querySelector(`[data-message-id="${CSS.escape(id)}"]`);if(row){row.scrollIntoView({behavior:'smooth',block:'center'});row.classList.add('flash');setTimeout(()=>row.classList.remove('flash'),1400);}}

  function bindComposer(c,state,pro){
    const input=document.getElementById('chatpro-input');if(!input)return;
    const draftSave=()=>{if(ui.editing)return;pro.drafts[c.id]=input.value;savePro(pro);};
    input.addEventListener('input',()=>{input.style.height='auto';input.style.height=`${Math.min(150,input.scrollHeight)}px`;draftSave();});
    input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendCurrent(c,state,pro,input);}});
    document.getElementById('chatpro-send').onclick=()=>sendCurrent(c,state,pro,input);
    document.getElementById('chatpro-context-close')?.addEventListener('click',()=>{ui.replyTo='';ui.editing='';render();});
    document.getElementById('chatpro-attach').onclick=()=>{ui.attach=!ui.attach;ui.emoji=false;ui.sticker=false;render();};
    document.getElementById('chatpro-emoji').onclick=()=>{ui.emoji=!ui.emoji;ui.attach=false;ui.sticker=false;render();};
    document.getElementById('chatpro-voice').onclick=()=>toggleVoice(c,state);
    document.getElementById('chatpro-schedule').onclick=()=>openScheduleSheet(c,state,pro,input.value.trim());
    document.querySelectorAll('[data-insert-emoji]').forEach(b=>b.onclick=()=>{const pos=input.selectionStart??input.value.length;input.value=input.value.slice(0,pos)+b.dataset.insertEmoji+input.value.slice(pos);input.focus();});
    document.querySelectorAll('[data-close-picker]').forEach(b=>b.onclick=()=>{ui.emoji=false;ui.sticker=false;render();});
    document.querySelectorAll('[data-attach-kind]').forEach(b=>b.onclick=()=>handleAttachmentChoice(b.dataset.attachKind,c,state));
    document.getElementById('chatpro-media-file')?.addEventListener('change',e=>handleMedia(e.target.files?.[0],c,state));
    document.getElementById('chatpro-doc-file')?.addEventListener('change',e=>handleDocument(e.target.files?.[0],c,state));
    document.querySelectorAll('[data-send-sticker]').forEach(b=>b.onclick=()=>appendMessage(c,state,{type:'sticker',text:b.dataset.sendSticker}));
    document.querySelectorAll('[data-provider]').forEach(b=>b.onclick=()=>{const w=window.open(b.dataset.provider,'_blank','noopener,noreferrer');if(w)w.opener=null;});
    document.getElementById('chatpro-gif-send')?.addEventListener('click',()=>{const url=document.getElementById('chatpro-gif-url').value.trim();if(!/^https?:\/\//i.test(url)){showToast('Paste a valid GIF URL');return;}appendMessage(c,state,{type:'gif',data:url});});
    document.getElementById('chatpro-make-sticker')?.addEventListener('click',()=>openStickerMaker(c,state));
  }
  function sendCurrent(c,state,pro,input){const text=input.value.trim();if(!text)return;if(ui.editing){const m=c.messages.find(x=>x.id===ui.editing);if(m){m.text=text;m.edited=true;m.at=now();}ui.editing='';pro.drafts[c.id]='';savePro(pro);saveChat(state);render();return;}appendMessage(c,state,{type:'text',text,replyTo:ui.replyTo||undefined});ui.replyTo='';pro.drafts[c.id]='';savePro(pro);}
  function appendMessage(c,state,payload){const m={id:uid('msg'),mine:true,at:now(),status:'read',reactions:{},...payload};c.messages.push(m);c.unread=0;if(saveChat(state)){resetTransient();ui.mobileThread=true;render();}else c.messages.pop();}
  function handleAttachmentChoice(kind,c,state){ui.attach=false;if(kind==='media'){document.getElementById('chatpro-media-file')?.click();return;}if(kind==='document'){document.getElementById('chatpro-doc-file')?.click();return;}if(kind==='contact'){openContactSheet(c,state);return;}if(kind==='location'){shareLocation(c,state);return;}if(kind==='poll'){openPollSheet(c,state);return;}if(kind==='sticker'){ui.sticker=true;render();}}
  async function handleMedia(file,c,state){if(!file)return;const isVideo=file.type.startsWith('video/'),max=isVideo?MAX_VIDEO:MAX_IMAGE;if(file.size>max){showToast(`${isVideo?'Video':'Image'} is too large for local browser storage`);return;}const data=await fileData(file);appendMessage(c,state,{type:isVideo?'video':'image',data,name:file.name});}
  async function handleDocument(file,c,state){if(!file)return;if(file.size>MAX_DOC){showToast('Document is too large for local browser storage');return;}const data=await fileData(file);appendMessage(c,state,{type:'file',data,name:file.name,sizeLabel:formatBytes(file.size)});}
  function fileData(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=reject;r.readAsDataURL(file);});}
  function formatBytes(n){if(n<1024)return `${n} B`;if(n<1048576)return `${Math.round(n/1024)} KB`;return `${(n/1048576).toFixed(1)} MB`;}

  async function toggleVoice(c,state){const button=document.getElementById('chatpro-voice');if(voiceRecorder&&voiceRecorder.state==='recording'){voiceRecorder.stop();if(button)button.textContent='🎙';return;}if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==='undefined'){showToast('Voice recording is not supported in this browser');return;}try{voiceStream=await navigator.mediaDevices.getUserMedia({audio:true});voiceChunks=[];voiceConversationId=c.id;voiceRecorder=new MediaRecorder(voiceStream);voiceRecorder.ondataavailable=e=>{if(e.data.size)voiceChunks.push(e.data);};voiceRecorder.onstop=async()=>{const blob=new Blob(voiceChunks,{type:voiceRecorder?.mimeType||'audio/webm'});voiceStream?.getTracks().forEach(t=>t.stop());voiceStream=null;voiceRecorder=null;if(blob.size>MAX_VOICE){showToast('Voice note is too long for local storage');return;}const fresh=chatState(),conv=findConversation(fresh,voiceConversationId);voiceConversationId='';if(!conv)return;const data=await fileData(blob);appendMessage(conv,fresh,{type:'voice',data});};voiceRecorder.start();if(button)button.textContent='■';}catch{showToast('Microphone permission was not granted');}}
  function cancelVoiceIfLeaving(current){if(current.split('/')[0]==='chat')return;if(voiceRecorder&&voiceRecorder.state==='recording'){try{voiceRecorder.stop();}catch{}voiceStream?.getTracks().forEach(t=>t.stop());voiceStream=null;voiceRecorder=null;voiceConversationId='';}}

  function bindInfo(c,state,pro){document.querySelectorAll('[data-info-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.infoAction,meta=metaFor(pro,c.id);if(a==='mute')meta.muted=!meta.muted;if(a==='pin')meta.pinned=!meta.pinned;if(a==='archive')meta.archived=!meta.archived;if(a==='block'){toggleBlock(c,state);return;}if(a==='clear'){if(confirm(`Clear all messages in ${c.name}?`)){c.messages=[];saveChat(state);render();}return;}if(a==='delete'){if(confirm(`Delete conversation with ${c.name}?`)){state.conversations=state.conversations.filter(x=>x.id!==c.id);saveChat(state);ui.info=false;render();}return;}savePro(pro);render();});document.getElementById('chatpro-add-member')?.addEventListener('click',()=>openAddMemberSheet(c,state));}
  function toggleBlock(c,state){const i=state.blocked.indexOf(c.id);if(i>=0)state.blocked.splice(i,1);else state.blocked.push(c.id);saveChat(state);render();}

  function openConversationMenu(id,state,pro){const c=findConversation(state,id),meta=metaFor(pro,id),layer=document.getElementById('chatpro-layer');if(!c||!layer)return;layer.innerHTML=`<div class="chatpro-popover conv-pop"><button data-conv-action="pin">${meta.pinned?'Unpin':'Pin'} chat</button><button data-conv-action="mute">${meta.muted?'Unmute':'Mute notifications'}</button><button data-conv-action="unread">Mark as unread</button><button data-conv-action="archive">${meta.archived?'Unarchive':'Archive'}</button><button data-conv-action="delete" class="danger-text">Delete chat</button></div><div class="chatpro-layer-dismiss"></div>`;layer.querySelector('.chatpro-layer-dismiss').onclick=()=>layer.innerHTML='';layer.querySelectorAll('[data-conv-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.convAction;if(a==='pin')meta.pinned=!meta.pinned;if(a==='mute')meta.muted=!meta.muted;if(a==='unread')meta.unread=true;if(a==='archive')meta.archived=!meta.archived;if(a==='delete'){if(confirm(`Delete ${c.name}?`))state.conversations=state.conversations.filter(x=>x.id!==id);saveChat(state);}savePro(pro);render();});}
  function openRailMenu(kind){const layer=document.getElementById('chatpro-layer');if(!layer)return;layer.innerHTML=`<div class="chatpro-popover rail-pop"><button data-rail-action="new">New ${kind==='group'?'group':'chat'}</button><button data-rail-action="saved">Saved Messages</button><button data-rail-action="archived">Archived chats</button><button data-rail-action="readall">Mark all as read</button></div><div class="chatpro-layer-dismiss"></div>`;layer.querySelector('.chatpro-layer-dismiss').onclick=()=>layer.innerHTML='';layer.querySelectorAll('[data-rail-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.railAction;if(a==='new')openNewChatSheet(kind,chatState());if(a==='saved'){const st=chatState();st.selected.private='saved-messages';saveChat(st);setHash(`chat/${encodeURIComponent('Private chats')}`);}if(a==='archived'){ui.filter='archived';render();}if(a==='readall'){const st=chatState(),p=proState();st.conversations.filter(c=>c.kind===kind).forEach(c=>{c.unread=0;metaFor(p,c.id).unread=false;});saveChat(st);savePro(p);render();}});}

  function sheet(inner,id='chatpro-sheet'){const root=document.getElementById('overlay-root');if(!root)return null;root.innerHTML=`<div class="entity-sheet-overlay" id="${id}-overlay"><section class="entity-sheet chatpro-sheet">${inner}</section></div>`;const close=()=>root.innerHTML='';root.querySelector('[data-sheet-close]')?.addEventListener('click',close);root.querySelector(`#${id}-overlay`)?.addEventListener('click',e=>{if(e.target.id===`${id}-overlay`)close();});return {root,close};}
  function openNewChatSheet(kind,state){const title=kind==='group'?'Create group':kind==='unknown'?'New anonymous message':'New private chat';const label=kind==='group'?'Group name':kind==='unknown'?'Topic':'Student name';const s=sheet(`<div class="entity-sheet-handle"></div><div class="entity-sheet-head"><div><div class="eyebrow">Dafatii Chat</div><h2>${title}</h2></div><button class="icon-btn" data-sheet-close>×</button></div><form id="chatpro-new-form"><div class="field"><label>${label}</label><input id="chatpro-new-name" maxlength="70" required placeholder="${kind==='group'?'e.g. Calculus Night Crew':kind==='unknown'?'e.g. Lecture 6 notes':'e.g. Sara'}"></div>${kind==='group'?'<div class="field"><label>Members <span class="field-optional">Optional</span></label><input id="chatpro-new-members" maxlength="180" placeholder="Lina, Omar, Noor"></div>':''}${kind==='unknown'?'<p class="sr-sheet-help">Your normal display name is hidden in this conversation.</p>':''}<button class="btn btn-primary entity-submit">${kind==='group'?'Create group':'Start chat'}</button></form>`);if(!s)return;document.getElementById('chatpro-new-form').onsubmit=e=>{e.preventDefault();const raw=document.getElementById('chatpro-new-name').value.trim();if(!raw)return;const id=uid(kind),name=kind==='unknown'?`Unknown #${Math.floor(1000+Math.random()*9000)}`:raw,participants=kind==='group'?['You',...document.getElementById('chatpro-new-members').value.split(',').map(x=>x.trim()).filter(Boolean)]:undefined;state.conversations.unshift({id,kind,name,topic:kind==='unknown'?raw:'',avatar:kind==='group'?'◎':kind==='unknown'?'?':raw[0].toUpperCase(),status:kind==='group'?`${participants.length} members`:kind==='unknown'?'anonymous relay':'new chat',participants,messages:[]});state.selected[kind]=id;saveChat(state);s.close();ui.mobileThread=true;render();};}
  function openContactSheet(c,state){const s=sheet(`<div class="entity-sheet-handle"></div><div class="entity-sheet-head"><div><div class="eyebrow">Attachment</div><h2>Share contact</h2></div><button class="icon-btn" data-sheet-close>×</button></div><form id="chatpro-contact-form"><div class="field"><label>Name</label><input id="chatpro-contact-name" required></div><div class="field"><label>Phone / username</label><input id="chatpro-contact-value" required></div><button class="btn btn-primary entity-submit">Send contact</button></form>`);if(!s)return;document.getElementById('chatpro-contact-form').onsubmit=e=>{e.preventDefault();appendMessage(c,state,{type:'contact',contactName:document.getElementById('chatpro-contact-name').value.trim(),contactValue:document.getElementById('chatpro-contact-value').value.trim()});s.close();};}
  function shareLocation(c,state){if(!navigator.geolocation){showToast('Location is unavailable in this browser');return;}showToast('Requesting your location…');navigator.geolocation.getCurrentPosition(pos=>appendMessage(c,state,{type:'location',lat:pos.coords.latitude,lon:pos.coords.longitude}),()=>showToast('Location permission was not granted'),{enableHighAccuracy:false,timeout:8000});}
  function openPollSheet(c,state){const s=sheet(`<div class="entity-sheet-handle"></div><div class="entity-sheet-head"><div><div class="eyebrow">Group tool</div><h2>Create poll</h2></div><button class="icon-btn" data-sheet-close>×</button></div><form id="chatpro-poll-form"><div class="field"><label>Question</label><input id="chatpro-poll-q" maxlength="140" required></div><div class="field"><label>Options</label><input id="chatpro-poll-options" placeholder="Option 1, Option 2, Option 3" required></div><button class="btn btn-primary entity-submit">Send poll</button></form>`);if(!s)return;document.getElementById('chatpro-poll-form').onsubmit=e=>{e.preventDefault();const question=document.getElementById('chatpro-poll-q').value.trim(),options=document.getElementById('chatpro-poll-options').value.split(',').map(x=>x.trim()).filter(Boolean).slice(0,8);if(options.length<2){showToast('Add at least two options');return;}appendMessage(c,state,{type:'poll',question,options:options.map(text=>({text,votes:0,voted:false}))});s.close();};}
  function openStickerMaker(c,state){const s=sheet(`<div class="entity-sheet-handle"></div><div class="entity-sheet-head"><div><div class="eyebrow">Sticker maker</div><h2>Make sticker</h2></div><button class="icon-btn" data-sheet-close>×</button></div><form id="chatpro-sticker-form"><div class="field"><label>Emoji</label><input id="chatpro-sticker-emoji" value="✨" maxlength="4"></div><div class="field"><label>Text</label><input id="chatpro-sticker-text" maxlength="40" required placeholder="LOCKED IN"></div><button class="btn btn-primary entity-submit">Send sticker</button></form>`);if(!s)return;document.getElementById('chatpro-sticker-form').onsubmit=e=>{e.preventDefault();appendMessage(c,state,{type:'custom-sticker',emoji:document.getElementById('chatpro-sticker-emoji').value.trim()||'✨',text:document.getElementById('chatpro-sticker-text').value.trim()});s.close();};}
  function openForwardSheet(message,state){const choices=state.conversations.filter(c=>c.id!=='').slice(0,20);const s=sheet(`<div class="entity-sheet-handle"></div><div class="entity-sheet-head"><div><div class="eyebrow">Forward</div><h2>Choose chats</h2></div><button class="icon-btn" data-sheet-close>×</button></div><div class="chatpro-forward-list">${choices.map(c=>`<button data-forward-to="${esc(c.id)}"><span class="chatpro-avatar">${esc(c.avatar||c.name?.[0]||'?')}</span><strong>${esc(c.name)}</strong><small>${esc(subLabel(c.kind))}</small></button>`).join('')}</div>`);if(!s)return;s.root.querySelectorAll('[data-forward-to]').forEach(b=>b.onclick=()=>{const fresh=chatState(),dest=findConversation(fresh,b.dataset.forwardTo);if(!dest)return;const copy=clone(message);copy.id=uid('msg');copy.mine=true;copy.at=now();copy.status='read';copy.forwarded=true;delete copy.replyTo;dest.messages.push(copy);saveChat(fresh);s.close();showToast(`Forwarded to ${dest.name}`);});}
  function openDeleteMessageSheet(m,c,state){const s=sheet(`<div class="entity-sheet-handle"></div><div class="entity-sheet-head"><div><div class="eyebrow">Message</div><h2>Delete message?</h2></div><button class="icon-btn" data-sheet-close>×</button></div><div class="chatpro-delete-options"><button class="btn btn-ghost" id="chatpro-delete-me">Delete for me</button>${m.mine?'<button class="btn btn-danger" id="chatpro-delete-all">Delete for everyone</button>':''}</div>`);if(!s)return;document.getElementById('chatpro-delete-me').onclick=()=>{c.messages=c.messages.filter(x=>x.id!==m.id);saveChat(state);s.close();render();};document.getElementById('chatpro-delete-all')?.addEventListener('click',()=>{m.deleted=true;m.text='';m.data='';m.edited=false;saveChat(state);s.close();render();});}
  function openScheduleSheet(c,state,pro,currentText){const s=sheet(`<div class="entity-sheet-handle"></div><div class="entity-sheet-head"><div><div class="eyebrow">Telegram-style tool</div><h2>Schedule message</h2></div><button class="icon-btn" data-sheet-close>×</button></div><form id="chatpro-schedule-form"><div class="field"><label>Message</label><textarea id="chatpro-schedule-text" class="academic-notes" maxlength="5000" required>${esc(currentText)}</textarea></div><div class="field"><label>Send at</label><input id="chatpro-schedule-at" type="datetime-local" required></div><button class="btn btn-primary entity-submit">Schedule</button></form>`);if(!s)return;const dt=document.getElementById('chatpro-schedule-at');dt.value=new Date(now()+3600000).toISOString().slice(0,16);document.getElementById('chatpro-schedule-form').onsubmit=e=>{e.preventDefault();const text=document.getElementById('chatpro-schedule-text').value.trim(),at=new Date(dt.value).getTime();if(!text||!Number.isFinite(at)||at<=now()){showToast('Choose a future time');return;}pro.scheduled.push({id:uid('scheduled'),conversationId:c.id,text,at});savePro(pro);s.close();showToast('Message scheduled');};}
  function processScheduled(state,pro){const due=pro.scheduled.filter(x=>x.at<=now()),future=pro.scheduled.filter(x=>x.at>now());if(!due.length)return;due.forEach(x=>{const c=findConversation(state,x.conversationId);if(c)c.messages.push({id:uid('msg'),mine:true,type:'text',text:x.text,at:x.at,status:'read',reactions:{},scheduled:true});});pro.scheduled=future;saveChat(state);savePro(pro);}
  function openAddMemberSheet(c,state){const s=sheet(`<div class="entity-sheet-handle"></div><div class="entity-sheet-head"><div><div class="eyebrow">Group</div><h2>Add member</h2></div><button class="icon-btn" data-sheet-close>×</button></div><form id="chatpro-member-form"><div class="field"><label>Student name</label><input id="chatpro-member-name" required maxlength="60"></div><button class="btn btn-primary entity-submit">Add member</button></form>`);if(!s)return;document.getElementById('chatpro-member-form').onsubmit=e=>{e.preventDefault();const name=document.getElementById('chatpro-member-name').value.trim();c.participants=c.participants||['You'];if(name&&!c.participants.includes(name))c.participants.push(name);c.status=`${c.participants.length} members`;saveChat(state);s.close();render();};}
  function openCallSheet(c,type){const s=sheet(`<div class="entity-sheet-handle"></div><div class="chatpro-call-sheet"><span class="chatpro-avatar xxlarge">${esc(c.avatar||c.name?.[0]||'?')}</span><h2>${esc(c.name)}</h2><p>${type==='video'?'Video':'Voice'} call interface</p><div class="chatpro-call-state"><i></i><span>Ready</span></div><div class="chatpro-call-controls"><button data-call-control="mic">🎙</button>${type==='video'?'<button data-call-control="camera">▣</button>':''}<button class="end" data-sheet-close>☎</button></div><small>Realtime peer calling requires backend signaling/WebRTC integration; this build provides the complete call surface without pretending a remote connection exists.</small></div>`);if(!s)return;s.root.querySelectorAll('[data-call-control]').forEach(b=>b.onclick=()=>b.classList.toggle('off'));}
})();
