(() => {
  'use strict';
  const esc=value=>escapeHtml(value??'');
  const permissionLabels={add_content:'Add content',edit_content:'Edit content',remove_content:'Remove content',manage_students:'Add/remove students',review_applications:'Accept/reject applications',manage_representers:'Make representers',manage_settings:'Change dafaa access'};
  const panel={members:[],events:[],users:[],dafat:[],overview:null,error:''};
  LABELS.admin='Admin Panel';LABELS.representer='Representer Panel';

  function representativePage(){
    const dafaa=window.DafatiiDafat.active(),admin=window.DafatiiAuth.user?.platformRole==='admin',membership=dafaa.membership||(admin?{role:'owner',permissions:{}}:null);
    if(!dafaa.id||(!admin&&!['owner','representer'].includes(membership?.role)))return denied('Representer access is required for the active dafaa.');
    const p=membership.permissions||{},owner=membership.role==='owner'||window.DafatiiAuth.user?.platformRole==='admin';
    return `<section class="suite-page role-panel"><div class="suite-head"><div><div class="eyebrow">${esc(dafaa.name)} · Dafaa operations</div><h1>Representer panel</h1><p>Manage enrollment, access and delegated advantages for this dafaa.</p></div><button class="btn btn-ghost" id="role-refresh">Refresh</button></div>
      ${panel.error?`<div class="panel-alert">${esc(panel.error)}</div>`:''}
      ${p.manage_settings||owner?settingsForm(dafaa):''}
      ${p.manage_students||p.manage_representers||owner?`<article class="panel-card"><h2>Add a registered member</h2><form id="member-add" class="panel-inline"><input type="email" name="email" placeholder="student@example.com" required><select name="role"><option value="student">Student</option>${p.manage_representers||owner?'<option value="representer">Representer</option>':''}</select><button class="btn btn-primary">Add</button></form></article>`:''}
      <article class="panel-card"><div class="panel-title"><h2>Members and applications</h2><span>${panel.members.length}</span></div><div class="member-list" id="member-list">${panel.members.length?panel.members.map(member=>memberRow(member,membership,owner)).join(''):'<p class="muted">Loading members…</p>'}</div></article>
      <article class="panel-card"><h2>Recent audit trail</h2><div class="audit-list">${panel.events.length?panel.events.map(event=>`<div><strong>${esc(event.action)}</strong><span>${esc(event.actorName)} · ${new Date(event.createdAt).toLocaleString()}</span></div>`).join(''):'<p class="muted">No recent actions.</p>'}</div></article>
    </section>`;
  }
  function settingsForm(dafaa){return `<article class="panel-card"><h2>Dafaa access</h2><form id="dafaa-settings" class="panel-grid"><label>Name<input name="name" value="${esc(dafaa.name)}" required></label><label>Pricing<select name="pricing"><option value="free" ${dafaa.pricing==='free'?'selected':''}>Free</option><option value="paid" ${dafaa.pricing==='paid'?'selected':''}>Paid</option></select></label><label>Price in minor units<input name="priceMinor" type="number" min="0" value="${Number(dafaa.priceMinor||0)}"></label><label>Visibility<select name="visibility"><option value="public" ${dafaa.visibility==='public'?'selected':''}>Public</option><option value="private" ${dafaa.visibility==='private'?'selected':''}>Private by code</option></select></label><label>Join policy<select name="joinPolicy"><option value="direct" ${dafaa.joinPolicy==='direct'?'selected':''}>Direct join</option><option value="approval" ${dafaa.joinPolicy==='approval'?'selected':''}>Needs acceptance</option></select></label><label>New access code<input name="accessCode" type="password" minlength="6" maxlength="64" placeholder="Leave blank to keep current"></label><button class="btn btn-primary">Save dafaa access</button></form><p class="auth-note">Enrollment code: <strong>${esc(dafaa.enrollmentCode)}</strong>. Paid enrollment remains pending until manually verified.</p></article>`;}
  function memberRow(member,current,owner){
    const canReview=current.role==='owner'||current.permissions?.review_applications,canStudents=current.role==='owner'||current.permissions?.manage_students,canReps=current.role==='owner'||current.permissions?.manage_representers;
    const manage=member.role==='student'?canStudents:canReps;
    return `<div class="member-row" data-user="${esc(member.userId)}"><div class="member-who"><strong>${esc(member.displayName)}</strong><span>${esc(member.email)} · ${esc(member.role)} · ${esc(member.status)}</span></div><div class="member-actions">${['pending','payment_pending'].includes(member.status)&&canReview?`<button class="btn btn-primary btn-small" data-member-status="active">${member.status==='payment_pending'?'Verify payment':'Accept'}</button><button class="btn btn-ghost btn-small" data-member-status="rejected">Reject</button>`:''}${member.status==='active'&&member.role==='student'&&canReps?'<button class="btn btn-ghost btn-small" data-member-role="representer">Make representer</button>':''}${member.role==='representer'&&owner?'<button class="btn btn-ghost btn-small" data-permissions>Advantages</button>':''}${manage&&member.role!=='owner'?'<button class="btn btn-danger btn-small" data-member-remove>Remove</button>':''}</div></div>`;
  }

  function adminPage(){
    if(window.DafatiiAuth.user?.platformRole!=='admin')return denied('Administrator access is required.');
    const overview=panel.overview||{};
    return `<section class="suite-page role-panel"><div class="suite-head"><div><div class="eyebrow">Platform operations</div><h1>Admin panel</h1><p>Full control over accounts, dafat, enrollment and representers.</p></div><button class="btn btn-ghost" id="admin-refresh">Refresh</button></div>${panel.error?`<div class="panel-alert">${esc(panel.error)}</div>`:''}
      <div class="admin-stats">${[['Users',overview.users],['Active dafat',overview.dafat],['Enrollments',overview.memberships],['Pending',overview.pending]].map(([label,value])=>`<article><strong>${Number(value||0)}</strong><span>${label}</span></article>`).join('')}</div>
      <article class="panel-card"><div class="panel-title"><h2>All dafat</h2><button class="btn btn-primary btn-small" data-extra="dafati">Create a Dafaa</button></div><div class="admin-table">${panel.dafat.map(dafaa=>`<div class="admin-row"><div><strong>${esc(dafaa.name)}</strong><span>${esc(dafaa.enrollmentCode)} · ${esc(dafaa.status)} · ${dafaa.memberCount} members</span></div><div><button class="btn btn-ghost btn-small" data-admin-open="${esc(dafaa.id)}">Open</button>${dafaa.status==='active'?`<button class="btn btn-danger btn-small" data-admin-archive="${esc(dafaa.id)}">Archive</button>`:''}</div></div>`).join('')||'<p class="muted">Loading dafat…</p>'}</div></article>
      <article class="panel-card"><h2>Accounts</h2><div class="admin-table">${panel.users.map(user=>adminUserRow(user)).join('')||'<p class="muted">Loading accounts…</p>'}</div></article>
    </section>`;
  }
  function adminUserRow(user){return `<form class="admin-row admin-user" data-admin-user="${esc(user.id)}"><div><strong>${esc(user.displayName)}</strong><span>${esc(user.email)} · ${user.dafaaCount} dafat</span></div><select name="accountType"><option value="student" ${user.accountType==='student'?'selected':''}>Student</option><option value="representer" ${user.accountType==='representer'?'selected':''}>Representer</option></select><select name="studentStage"><option value="school" ${user.studentStage==='school'?'selected':''}>School</option><option value="university" ${user.studentStage==='university'?'selected':''}>University</option><option value="independent" ${user.studentStage==='independent'?'selected':''}>Independent</option></select><select name="platformRole"><option value="student" ${user.platformRole==='student'?'selected':''}>Standard</option><option value="admin" ${user.platformRole==='admin'?'selected':''}>Admin</option></select><select name="status"><option value="active" ${user.status==='active'?'selected':''}>Active</option><option value="disabled" ${user.status==='disabled'?'selected':''}>Disabled</option><option value="deleted" ${user.status==='deleted'?'selected':''}>Deleted</option></select><button class="btn btn-primary btn-small">Save</button></form>`;}
  function denied(message){return `<section class="empty-state"><div class="empty-icon">⛔</div><h1>Access denied</h1><p>${esc(message)}</p></section>`;}

  const previousContent=workspaceContent;workspaceContent=function(page,parts,title){if(page==='representer')return representativePage();if(page==='admin')return adminPage();return previousContent(page,parts,title);};
  const previousWorkspace=workspace;workspace=function(current){previousWorkspace(current);const page=current.split('/')[0];applyRoleMode();if(page==='representer')bindRepresentative();if(page==='admin')bindAdmin();if(page==='dashboard'&&['owner','representer'].includes(window.DafatiiDafat.active().membership?.role))addDashboardPanelButton();};
  function applyRoleMode(){const dafaa=window.DafatiiDafat.active(),editable=['owner','representer'].includes(dafaa.membership?.role)&&(dafaa.membership.role==='owner'||['add_content','edit_content','remove_content'].some(key=>dafaa.membership.permissions?.[key]))||window.DafatiiAuth.user?.platformRole==='admin';document.body.classList.toggle('dafaa-readonly',!editable);}
  function addDashboardPanelButton(){
    const dashboard=document.querySelector('.suite-dashboard'),head=dashboard?.querySelector('.suite-head');
    if(!head||document.getElementById('representer-panel-button'))return;
    const dafaa=window.DafatiiDafat.active(),button=document.createElement('button');
    button.type='button';
    button.id='representer-panel-button';
    button.className='representer-panel-entry';
    button.setAttribute('aria-label',`Open Representer panel for ${dafaa.name||'active dafaa'}`);
    button.innerHTML=`<span class="representer-panel-entry-icon">${window.DafatiiIcons?.icon('representer')||''}</span><span class="representer-panel-entry-copy"><strong>Representer panel</strong><small>${esc(dafaa.name||'Manage the active dafaa')}</small></span><span class="representer-panel-entry-arrow">${window.DafatiiIcons?.icon('arrow-right')||''}</span>`;
    button.onclick=()=>setHash('representer');
    head.insertAdjacentElement('afterend',button);
  }

  async function loadRepresentative(){const id=window.DafatiiDafat.active().id;if(!id)return;try{const [members,audit]=await Promise.all([window.DafatiiApi.request(`/dafat/${id}/members`,{idempotent:true}),window.DafatiiApi.request(`/dafat/${id}/audit`,{idempotent:true})]);panel.members=members.members;panel.events=audit.events;panel.error='';}catch(error){panel.error=error.message;}render();}
  function bindRepresentative(){
    if(!panel.members.length&&!panel.error)void loadRepresentative();document.getElementById('role-refresh')?.addEventListener('click',loadRepresentative);
    document.getElementById('dafaa-settings')?.addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));data.priceMinor=Number(data.priceMinor);if(!data.accessCode)delete data.accessCode;try{await window.DafatiiDafat.updateDafaa(window.DafatiiDafat.active().id,data);panel.error='';}catch(error){panel.error=error.message;}render();});
    document.getElementById('member-add')?.addEventListener('submit',async e=>{e.preventDefault();try{await window.DafatiiApi.request(`/dafat/${window.DafatiiDafat.active().id}/members`,{method:'POST',body:Object.fromEntries(new FormData(e.currentTarget))});panel.members=[];await loadRepresentative();}catch(error){panel.error=error.message;render();}});
    document.querySelectorAll('[data-member-status],[data-member-role],[data-member-remove],[data-permissions]').forEach(button=>button.onclick=()=>memberAction(button));
  }
  async function memberAction(button){const row=button.closest('[data-user]'),userId=row.dataset.user,id=window.DafatiiDafat.active().id;try{if(button.hasAttribute('data-member-remove'))await window.DafatiiApi.request(`/dafat/${id}/members/${userId}`,{method:'DELETE'});else if(button.hasAttribute('data-permissions'))return permissionDialog(userId);else await window.DafatiiApi.request(`/dafat/${id}/members/${userId}`,{method:'PATCH',body:button.dataset.memberStatus?{status:button.dataset.memberStatus}:{role:button.dataset.memberRole}});panel.members=[];await loadRepresentative();}catch(error){panel.error=error.message;render();}}
  function permissionDialog(userId){const member=panel.members.find(item=>item.userId===userId),root=document.getElementById('overlay-root');root.innerHTML=`<div class="entity-sheet-overlay" id="permission-overlay"><section class="entity-sheet"><div class="entity-sheet-head"><h2>Representer advantages</h2><button class="icon-btn" id="permission-close">×</button></div><form id="permission-form" class="permission-list">${Object.entries(permissionLabels).map(([key,label])=>`<label><input type="checkbox" name="${key}" ${member.permissions?.[key]?'checked':''}> ${esc(label)}</label>`).join('')}<button class="btn btn-primary">Save advantages</button></form></section></div>`;const close=()=>root.innerHTML='';document.getElementById('permission-close').onclick=close;document.getElementById('permission-form').onsubmit=async e=>{e.preventDefault();const permissions=Object.fromEntries(Object.keys(permissionLabels).map(key=>[key,e.currentTarget.elements[key].checked]));try{await window.DafatiiApi.request(`/dafat/${window.DafatiiDafat.active().id}/members/${userId}`,{method:'PATCH',body:{permissions}});close();panel.members=[];await loadRepresentative();}catch(error){panel.error=error.message;close();render();}};}

  async function loadAdmin(){try{const [overview,users,dafat]=await Promise.all([window.DafatiiApi.request('/admin/overview',{idempotent:true}),window.DafatiiApi.request('/admin/users',{idempotent:true}),window.DafatiiApi.request('/dafat?scope=admin',{idempotent:true})]);panel.overview=overview;panel.users=users.users;panel.dafat=dafat.dafat;panel.error='';}catch(error){panel.error=error.message;}render();}
  function bindAdmin(){if(!panel.overview&&!panel.error)void loadAdmin();document.getElementById('admin-refresh')?.addEventListener('click',loadAdmin);document.querySelectorAll('[data-admin-user]').forEach(form=>form.onsubmit=async e=>{e.preventDefault();try{await window.DafatiiApi.request(`/admin/users/${form.dataset.adminUser}`,{method:'PATCH',body:Object.fromEntries(new FormData(form))});await loadAdmin();}catch(error){panel.error=error.message;render();}});document.querySelectorAll('[data-admin-open]').forEach(button=>button.onclick=async()=>{await window.DafatiiDafat.switchDafaa(button.dataset.adminOpen);setHash('representer');});document.querySelectorAll('[data-admin-archive]').forEach(button=>button.onclick=async()=>{if(!confirm('Archive this dafaa?'))return;try{await window.DafatiiApi.request(`/dafat/${button.dataset.adminArchive}`,{method:'DELETE'});await loadAdmin();}catch(error){panel.error=error.message;render();}});document.querySelectorAll('[data-extra]').forEach(button=>button.onclick=()=>setHash(button.dataset.extra));}
})();
