(() => {
  const SUITE_KEY='dafatii:studentSuite:v1';
  const EXAMS_KEY='dafatii:examSchedule';
  const SCHEDULE_KEY='dafatii:weeklySchedule';
  const ROOM_KEY='dafatii:studyRoomState:v1';
  const CHAT_KEY='dafatii:chatState:v1';
  const esc=v=>escapeHtml(v??'');
  const now=()=>Date.now();
  const uid=p=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;
  const DAY=86400000;
  const ui={materialFilter:'all',noteQuery:'',assignmentFilter:'all',deadlineFilter:'upcoming',oppFilter:'all'};

  const defaults={
    profile:{name:'Student',username:'student',school:'',course:'General studies',semester:'',bio:'',targetHours:8,studyLanguage:'English',interfaceLanguage:'English'},
    preferences:{motion:'full',density:'comfortable',weekStarts:'Sunday',defaultFocus:50,notifications:true},
    notes:[],resources:[],assignments:[],deadlines:[],focusLog:[],applications:[],scholarships:[],volunteer:[],support:[],activity:[]
  };

  const COURSE_TEMPLATES={
    'Computer Science':['Programming','Data Structures','Algorithms','Databases','Mathematics'],
    'Medicine':['Anatomy','Physiology','Biochemistry','Pharmacology','Pathology'],
    'Engineering':['Calculus','Physics','Mechanics','Circuits','Design'],
    'Business':['Accounting','Economics','Marketing','Finance','Management'],
    'High School':['Mathematics','Physics','Chemistry','Biology','English']
  };

  const WORK_SEEDS=[
    {id:'work-tutor',title:'Peer Tutor',org:'Campus Learning Hub',mode:'Flexible · 4–8h/week',tags:['Academic','Paid'],summary:'Help students with first-year mathematics and study planning.'},
    {id:'work-content',title:'Student Content Assistant',org:'Dafatii Community',mode:'Remote · Project based',tags:['Writing','Portfolio'],summary:'Create concise study guides and student-friendly learning resources.'},
    {id:'work-lab',title:'Undergraduate Lab Assistant',org:'Science Department',mode:'On campus · 6h/week',tags:['Science','Experience'],summary:'Support lab preparation, checklists and beginner practical sessions.'}
  ];
  const SCHOLARSHIP_SEEDS=[
    {id:'sch-merit',title:'Academic Momentum Award',amount:'$1,500',deadline:dateOffset(35),fit:'Strong grades + clear study goals',summary:'A student-success award focused on consistent academic progress.'},
    {id:'sch-community',title:'Community Builder Grant',amount:'$1,000',deadline:dateOffset(52),fit:'Volunteering + leadership',summary:'For students who improve peer learning or community access.'},
    {id:'sch-project',title:'Student Project Microgrant',amount:'$750',deadline:dateOffset(21),fit:'Prototype or research project',summary:'Small grant for student-led technical, creative or research projects.'}
  ];
  const VOLUNTEER_SEEDS=[
    {id:'vol-peer',title:'Peer Study Mentor',org:'Student Success Center',commitment:'2h/week',summary:'Support newer students with routines, planning and accountability.'},
    {id:'vol-library',title:'Library Digital Helper',org:'University Library',commitment:'One afternoon/month',summary:'Help students find digital resources and organize references.'},
    {id:'vol-stem',title:'STEM Outreach Volunteer',org:'Local Schools Network',commitment:'Weekend events',summary:'Join hands-on science and coding sessions for younger students.'}
  ];

  function dateOffset(days){const d=new Date(Date.now()+days*DAY);return d.toISOString().slice(0,10);}
  function readJSON(key,fallback){return window.DafatiiData.readJSON(key,fallback);}
  function writeJSON(key,value){try{window.DafatiiData.writeJSON(key,value);return true;}catch{showToast('Browser storage is full. Remove older local data and try again.');return false;}}
  function suite(){const raw=readJSON(SUITE_KEY,{});return {...defaults,...raw,profile:{...defaults.profile,...(raw.profile||{})},preferences:{...defaults.preferences,...(raw.preferences||{})},notes:Array.isArray(raw.notes)?raw.notes:[],resources:Array.isArray(raw.resources)?raw.resources:[],assignments:Array.isArray(raw.assignments)?raw.assignments:[],deadlines:Array.isArray(raw.deadlines)?raw.deadlines:[],focusLog:Array.isArray(raw.focusLog)?raw.focusLog:[],applications:Array.isArray(raw.applications)?raw.applications:[],scholarships:Array.isArray(raw.scholarships)?raw.scholarships:[],volunteer:Array.isArray(raw.volunteer)?raw.volunteer:[],support:Array.isArray(raw.support)?raw.support:[],activity:Array.isArray(raw.activity)?raw.activity:[]};}
  function saveSuite(v){writeJSON(SUITE_KEY,v);}
  function logActivity(v,type,text,route=''){v.activity.unshift({id:uid('act'),type,text,route,at:now()});v.activity=v.activity.slice(0,30);}
  function subjects(){return Array.isArray(state?.subjects)?state.subjects:[];}
  function subjectById(id){return subjects().find(s=>s.id===id);}
  function subjectName(id){return subjectById(id)?.name||'General';}
  function exams(){const v=readJSON(EXAMS_KEY,[]);return Array.isArray(v)?v:[];}
  function schedule(){const v=readJSON(SCHEDULE_KEY,[]);return Array.isArray(v)?v:[];}
  function roomState(){return readJSON(ROOM_KEY,{});}
  function chatState(){return readJSON(CHAT_KEY,{conversations:[]});}
  function fmtDate(v){if(!v)return 'No date';const d=new Date(`${v}T12:00:00`);return Number.isNaN(d.getTime())?v:d.toLocaleDateString([],{month:'short',day:'numeric',year:d.getFullYear()!==new Date().getFullYear()?'numeric':undefined});}
  function relativeDate(v){if(!v)return '';const d=new Date(`${v}T23:59:59`);const days=Math.ceil((d-Date.now())/DAY);if(days<0)return `${Math.abs(days)}d overdue`;if(days===0)return 'Today';if(days===1)return 'Tomorrow';return `in ${days} days`;}
  function relativeTime(t){const m=Math.max(0,Math.floor((now()-Number(t||now()))/60000));if(m<1)return 'now';if(m<60)return `${m}m ago`;const h=Math.floor(m/60);if(h<24)return `${h}h ago`;return `${Math.floor(h/24)}d ago`;}
  function subjectOptions(selected=''){return `<option value="">General / none</option>`+subjects().map(s=>`<option value="${esc(s.id)}" ${s.id===selected?'selected':''}>${esc(s.icon||'◇')} ${esc(s.name)}</option>`).join('');}
  function percent(n,d){return d?Math.round(n/d*100):0;}
  function safeUrl(raw){try{let s=String(raw||'').trim();if(!/^https?:\/\//i.test(s))s=`https://${s}`;const u=new URL(s);return ['http:','https:'].includes(u.protocol)?u.href:'';}catch{return '';}}

  MAIN_NAV.dashboard=['Overview','Recent materials','Progress'];
  MAIN_NAV.subjects=['All subjects','Notes','Resources','Assignments'];
  MAIN_NAV.calendar=['Schedule','Deadlines','Exams'];

  const previousWorkspaceContent=workspaceContent;
  workspaceContent=function(page,parts,title){
    const sub=decodeURIComponent(parts.slice(1).join('/')).toLowerCase();
    if(page==='dashboard'){
      if(!sub||sub==='overview')return dashboardView();
      if(sub==='recent materials')return recentMaterialsView();
      if(sub==='progress')return progressView();
    }
    if(page==='subjects'){
      if(sub==='notes')return notesView();
      if(sub==='resources')return resourcesView();
      if(sub==='assignments')return assignmentsView();
    }
    if(page==='calendar'&&sub==='deadlines')return deadlinesView();
    if(page==='settings')return settingsView();
    if(page==='profile')return profileView();
    if(page==='change-course')return courseView();
    if(page==='change-language')return languageView();
    if(page==='apply-work')return workView();
    if(page==='apply-scholarship')return scholarshipView();
    if(page==='volunteer')return volunteerView();
    if(page==='donate-us')return supportView();
    return previousWorkspaceContent(page,parts,title);
  };

  const previousWorkspace=workspace;
  workspace=function(current){
    previousWorkspace(current);
    const page=current.split('/')[0];
    const sub=decodeURIComponent(current.split('/').slice(1).join('/')).toLowerCase();
    if(page==='dashboard'&&(!sub||sub==='overview'))bindDashboard();
    if(page==='dashboard'&&sub==='recent materials')bindRecentMaterials();
    if(page==='dashboard'&&sub==='progress')bindProgress();
    if(page==='subjects'&&sub==='notes')bindNotes();
    if(page==='subjects'&&sub==='resources')bindResources();
    if(page==='subjects'&&sub==='assignments')bindAssignments();
    if(page==='calendar'&&sub==='deadlines')bindDeadlines();
    if(page==='settings')bindSettings();
    if(page==='profile')bindProfile();
    if(page==='change-course')bindCourse();
    if(page==='change-language')bindLanguage();
    if(page==='apply-work')bindWork();
    if(page==='apply-scholarship')bindScholarships();
    if(page==='volunteer')bindVolunteer();
    if(page==='donate-us')bindSupport();
    syncSuitePreferences();
  };

  function pageHead(eyebrow,title,copy,actions=''){return `<div class="suite-head"><div><div class="eyebrow">${esc(eyebrow)}</div><h1>${esc(title)}</h1><p>${esc(copy)}</p></div>${actions?`<div class="suite-head-actions">${actions}</div>`:''}</div>`;}
  function metric(icon,value,label,detail=''){return `<article class="suite-metric"><span>${icon}</span><div><strong>${esc(value)}</strong><p>${esc(label)}</p>${detail?`<small>${esc(detail)}</small>`:''}</div></article>`;}
  function empty(icon,title,text,button=''){return `<div class="suite-empty"><span>${icon}</span><h2>${esc(title)}</h2><p>${esc(text)}</p>${button}</div>`;}
  function progressBar(value,label=''){return `<div class="suite-progress"><div><span>${esc(label)}</span><strong>${Math.max(0,Math.min(100,Math.round(value)))}%</strong></div><i><b style="width:${Math.max(0,Math.min(100,value))}%"></b></i></div>`;}

  function dashboardView(){
    const v=suite(),as=v.assignments,es=exams();
    const openAssignments=as.filter(a=>a.status!=='done');
    const dueSoon=openAssignments.filter(a=>a.dueDate&&new Date(`${a.dueDate}T23:59:59`)-Date.now()<=7*DAY).length;
    const degreeVals=es.map(e=>Number(e.degree)).filter(Number.isFinite);
    const avg=degreeVals.length?(degreeVals.reduce((a,b)=>a+b,0)/degreeVals.length).toFixed(1):'—';
    const weekStart=Date.now()-7*DAY;
    const focusMin=v.focusLog.filter(x=>x.at>=weekStart).reduce((s,x)=>s+Number(x.minutes||0),0);
    const upcoming=deadlineItems(v).filter(x=>!x.done&&x.date).slice(0,5);
    const recent=recentMaterialItems(v).slice(0,5);
    const activeRoom=roomState().active;
    const chats=chatState().conversations||[];
    const unread=chats.reduce((s,c)=>s+Number(c.unread||0),0);
    return `<section class="suite-page suite-dashboard">
      ${pageHead(`Good ${daypart()}`,v.profile.name||'Student','Your academic command center: what needs attention, what changed, and where to go next.',`<button class="btn btn-ghost" data-suite-go="subjects/Notes">＋ Note</button><button class="btn btn-ghost" data-suite-go="subjects/Assignments">＋ Assignment</button><button class="btn btn-primary" id="suite-log-focus">▶ Log focus</button>`)}
      <div class="suite-metrics">${metric('✓',openAssignments.length,'open assignments',dueSoon?`${dueSoon} due within 7 days`:'Nothing urgent')}${metric('◷',`${Math.floor(focusMin/60)}h ${focusMin%60}m`,'focus this week',`${v.profile.targetHours||8}h weekly target`)}${metric('%',avg,'degree average',degreeVals.length?`${degreeVals.length} graded exams`:'Add degrees in Subjects')}${metric('◌',unread,'unread chats',activeRoom?'Study room active':'No active room')}</div>
      <div class="suite-dashboard-grid">
        <article class="suite-panel suite-priority"><div class="suite-panel-head"><div><span class="eyebrow">Next up</span><h2>Priority queue</h2></div><button data-suite-go="calendar/Deadlines">See deadlines →</button></div>${upcoming.length?`<div class="suite-list">${upcoming.map(deadlineRow).join('')}</div>`:empty('✓','Nothing urgent','Add an assignment or deadline and it will appear here.')}</article>
        <article class="suite-panel"><div class="suite-panel-head"><div><span class="eyebrow">Materials</span><h2>Recently touched</h2></div><button data-suite-go="dashboard/Recent%20materials">View all →</button></div>${recent.length?`<div class="suite-list">${recent.map(materialRow).join('')}</div>`:empty('◇','No recent materials','Create a note, resource, or lecture to populate this feed.')}</article>
        <article class="suite-panel suite-focus-panel"><div class="suite-panel-head"><div><span class="eyebrow">Focus</span><h2>This week</h2></div><button data-suite-go="dashboard/Progress">Progress →</button></div>${progressBar(Math.min(100,focusMin/60/(v.profile.targetHours||8)*100),'Weekly focus goal')}<div class="suite-mini-stats"><span><strong>${v.focusLog.filter(x=>x.at>=weekStart).length}</strong> sessions</span><span><strong>${assignmentCompletion(v)}%</strong> assignments done</span><span><strong>${subjects().length}</strong> subjects</span></div></article>
        <article class="suite-panel suite-links"><div class="suite-panel-head"><div><span class="eyebrow">Jump back in</span><h2>Study flow</h2></div></div><div class="suite-shortcuts"><button data-suite-go="study-rooms/My%20study%20rooms"><span>◎</span><strong>${activeRoom?'Continue room':'Study rooms'}</strong><small>${activeRoom?'Your live session is waiting':'Find accountability'}</small></button><button data-suite-go="chat/Private%20chats"><span>◌</span><strong>Chat</strong><small>${unread?`${unread} unread messages`:'Talk to classmates'}</small></button><button data-suite-go="calendar/Schedule"><span>□</span><strong>Schedule</strong><small>${schedule().length} weekly entries</small></button><button data-suite-go="subjects/Resources"><span>↗</span><strong>Resources</strong><small>${v.resources.length} saved links/files</small></button></div></article>
      </div>
    </section>`;
  }
  function daypart(){const h=new Date().getHours();return h<12?'morning':h<18?'afternoon':'evening';}
  function bindDashboard(){bindSuiteRoutes();document.getElementById('suite-log-focus')?.addEventListener('click',()=>openFocusSheet());}

  function recentMaterialItems(v){
    const notes=v.notes.map(n=>({id:n.id,type:'note',title:n.title||'Untitled note',subjectId:n.subjectId,detail:n.body||'',at:n.updatedAt||n.createdAt||0}));
    const resources=v.resources.map(r=>({id:r.id,type:'resource',title:r.title,subjectId:r.subjectId,detail:r.url||r.description||'',at:r.updatedAt||r.createdAt||0}));
    const lectures=[];subjects().forEach(s=>subjectLectures(s.id).forEach(l=>lectures.push({id:l.id,type:'lecture',title:l.name,subjectId:s.id,detail:l.notes||l.link||'',at:l.updatedAt||0,link:l.link})));
    return [...notes,...resources,...lectures].sort((a,b)=>Number(b.at||0)-Number(a.at||0));
  }
  function materialRow(m){return `<button class="suite-row suite-material-row" data-material-type="${esc(m.type)}" data-material-id="${esc(m.id)}" data-material-subject="${esc(m.subjectId||'')}"><span class="suite-row-icon">${m.type==='note'?'✎':m.type==='resource'?'↗':'▶'}</span><span><strong>${esc(m.title)}</strong><small>${esc(subjectName(m.subjectId))} · ${esc(m.type)}</small></span><time>${m.at?relativeTime(m.at):''}</time></button>`;}
  function recentMaterialsView(){const v=suite();const items=recentMaterialItems(v).filter(m=>ui.materialFilter==='all'||m.type===ui.materialFilter);return `<section class="suite-page">${pageHead('Dashboard · Materials','Recent materials','One timeline for notes, resources and lectures across every subject.',`<button class="btn btn-ghost" data-suite-go="subjects/Notes">＋ Note</button><button class="btn btn-primary" data-suite-go="subjects/Resources">＋ Resource</button>`)}<div class="suite-filterbar">${['all','note','resource','lecture'].map(x=>`<button class="${ui.materialFilter===x?'active':''}" data-material-filter="${x}">${x==='all'?'All':prettify(x)}</button>`).join('')}</div>${items.length?`<div class="suite-material-grid">${items.map(m=>`<article class="suite-material-card" data-material-type="${esc(m.type)}" data-material-id="${esc(m.id)}" data-material-subject="${esc(m.subjectId||'')}"><div class="suite-material-top"><span>${m.type==='note'?'✎':m.type==='resource'?'↗':'▶'}</span><small>${esc(m.type)}</small></div><h2>${esc(m.title)}</h2><p>${esc(String(m.detail||'').slice(0,150)||'No description yet.')}</p><footer><span>${esc(subjectName(m.subjectId))}</span><time>${m.at?relativeTime(m.at):''}</time></footer></article>`).join('')}</div>`:empty('◇','No matching materials','Add notes, resources, or lectures and they will appear here.')}</section>`;}
  function bindRecentMaterials(){bindSuiteRoutes();document.querySelectorAll('[data-material-filter]').forEach(b=>b.onclick=()=>{ui.materialFilter=b.dataset.materialFilter;render();});bindMaterialOpeners();}
  function bindMaterialOpeners(){document.querySelectorAll('[data-material-type][data-material-id]').forEach(el=>el.addEventListener('click',()=>openMaterial(el.dataset.materialType,el.dataset.materialId,el.dataset.materialSubject)));}
  function openMaterial(type,id,subjectId){const v=suite();if(type==='note'){const n=v.notes.find(x=>x.id===id);if(n)openNoteSheet(n.id);return;}if(type==='resource'){const r=v.resources.find(x=>x.id===id);if(r?.url){const url=safeUrl(r.url);if(url)window.open(url,'_blank','noopener,noreferrer');else openResourceSheet(r.id);}else if(r)openResourceSheet(r.id);return;}if(type==='lecture'){const l=subjectLectures(subjectId).find(x=>x.id===id);if(l?.link){const url=safeUrl(l.link);if(url)window.open(url,'_blank','noopener,noreferrer');else showToast('This lecture link is invalid.');}else setHash(`subjects/subject/${encodeURIComponent(subjectId)}/lectures`);}}

  function progressView(){
    const v=suite(),es=exams();const week=Date.now()-7*DAY,month=Date.now()-30*DAY;
    const weekMin=v.focusLog.filter(x=>x.at>=week).reduce((s,x)=>s+Number(x.minutes||0),0),monthMin=v.focusLog.filter(x=>x.at>=month).reduce((s,x)=>s+Number(x.minutes||0),0);
    const graded=es.map(e=>({...e,n:Number(e.degree)})).filter(e=>Number.isFinite(e.n));
    const overall=graded.length?graded.reduce((s,e)=>s+e.n,0)/graded.length:null;
    const subjectStats=subjects().map(s=>{const se=graded.filter(e=>e.subjectId===s.id);return {s,avg:se.length?se.reduce((a,e)=>a+e.n,0)/se.length:null,exams:se.length,lectures:subjectLectures(s.id).length,assignments:v.assignments.filter(a=>a.subjectId===s.id),notes:v.notes.filter(n=>n.subjectId===s.id).length};});
    return `<section class="suite-page">${pageHead('Dashboard · Progress','Progress','A practical view of study consistency, assignment execution and academic signals.',`<button class="btn btn-primary" id="suite-log-focus">＋ Log study session</button>`)}<div class="suite-metrics">${metric('◷',`${Math.round(weekMin/6)/10}h`,'focus this week',`${Math.round(monthMin/6)/10}h in 30 days`)}${metric('✓',`${assignmentCompletion(v)}%`,'assignment completion',`${v.assignments.filter(a=>a.status==='done').length}/${v.assignments.length} complete`)}${metric('%',overall===null?'—':overall.toFixed(1),'degree average',`${graded.length} graded exams`)}${metric('🔥',focusStreak(v),'study streak','days with logged focus')}</div><div class="suite-progress-layout"><article class="suite-panel"><div class="suite-panel-head"><div><span class="eyebrow">Goal</span><h2>Weekly focus</h2></div><strong>${Math.round(weekMin/60*10)/10}/${v.profile.targetHours||8}h</strong></div>${progressBar(Math.min(100,weekMin/60/(v.profile.targetHours||8)*100),'Focus target')}<div class="suite-focus-history">${v.focusLog.slice(0,8).map(x=>`<div><span>${esc(x.label||'Study session')}</span><strong>${esc(x.minutes)} min</strong><small>${relativeTime(x.at)}</small></div>`).join('')||'<p class="muted">No focus sessions logged yet.</p>'}</div></article><article class="suite-panel"><div class="suite-panel-head"><div><span class="eyebrow">Subjects</span><h2>Academic pulse</h2></div></div><div class="suite-subject-progress">${subjectStats.map(x=>`<button data-suite-go="subjects/subject/${encodeURIComponent(x.s.id)}/analysis"><span class="suite-subject-badge">${esc(x.s.icon||'◇')}</span><span><strong>${esc(x.s.name)}</strong><small>${x.lectures} lectures · ${x.assignments.filter(a=>a.status==='done').length}/${x.assignments.length} assignments</small></span><b>${x.avg===null?'—':x.avg.toFixed(1)}</b></button>`).join('')||'<p class="muted">Add subjects to see subject-level progress.</p>'}</div></article></div></section>`;
  }
  function assignmentCompletion(v){return percent(v.assignments.filter(a=>a.status==='done').length,v.assignments.length);}
  function focusStreak(v){const days=new Set(v.focusLog.map(x=>new Date(x.at).toDateString()));let streak=0,d=new Date();while(days.has(d.toDateString())){streak++;d=new Date(d.getTime()-DAY);}return `${streak}d`;}
  function bindProgress(){bindSuiteRoutes();document.getElementById('suite-log-focus')?.addEventListener('click',()=>openFocusSheet());}

  function notesView(){const v=suite();const q=ui.noteQuery.trim().toLowerCase();const notes=[...v.notes].sort((a,b)=>(b.pinned?1:0)-(a.pinned?1:0)||Number(b.updatedAt||0)-Number(a.updatedAt||0)).filter(n=>!q||`${n.title} ${n.body} ${n.tags||''}`.toLowerCase().includes(q));return `<section class="suite-page">${pageHead('Subjects · Notes','Notes','Capture class notes, revision summaries and questions, then keep them tied to the right subject.',`<button class="btn btn-primary" id="suite-add-note">＋ New note</button>`)}<label class="suite-search"><span>⌕</span><input id="suite-note-search" value="${esc(ui.noteQuery)}" placeholder="Search notes, tags, or text"></label>${notes.length?`<div class="suite-note-grid">${notes.map(noteCard).join('')}</div>`:empty('✎',q?'No notes match':'No notes yet',q?'Try another search.':'Create your first note and connect it to a subject.',`<button class="btn btn-primary" id="suite-empty-note">New note</button>`)}</section>`;}
  function noteCard(n){return `<article class="suite-note-card" data-note-id="${esc(n.id)}"><div class="suite-note-card-head"><span>${esc(subjectById(n.subjectId)?.icon||'✎')}</span><div><small>${esc(subjectName(n.subjectId))}</small><h2>${esc(n.title||'Untitled note')}</h2></div><button data-note-pin="${esc(n.id)}" title="${n.pinned?'Unpin':'Pin'}">${n.pinned?'★':'☆'}</button></div><p>${esc((n.body||'No note text yet.').slice(0,220))}</p><footer><span>${(n.tags||'').split(',').filter(Boolean).slice(0,3).map(t=>`<i>#${esc(t.trim())}</i>`).join('')}</span><time>${relativeTime(n.updatedAt||n.createdAt)}</time></footer></article>`;}
  function bindNotes(){bindSuiteRoutes();document.getElementById('suite-add-note')?.addEventListener('click',()=>openNoteSheet());document.getElementById('suite-empty-note')?.addEventListener('click',()=>openNoteSheet());document.getElementById('suite-note-search')?.addEventListener('input',e=>{ui.noteQuery=e.target.value;clearTimeout(bindNotes.t);bindNotes.t=setTimeout(render,180);});document.querySelectorAll('.suite-note-card').forEach(c=>c.addEventListener('click',e=>{if(e.target.closest('[data-note-pin]'))return;openNoteSheet(c.dataset.noteId);}));document.querySelectorAll('[data-note-pin]').forEach(b=>b.onclick=e=>{e.stopPropagation();const v=suite(),n=v.notes.find(x=>x.id===b.dataset.notePin);if(n){n.pinned=!n.pinned;n.updatedAt=now();saveSuite(v);render();}});}
  function openNoteSheet(id=''){const v=suite(),n=v.notes.find(x=>x.id===id);openSheet(n?'Edit note':'New note',`<form id="suite-note-form"><div class="field"><label>Title</label><input id="suite-note-title" maxlength="120" required value="${esc(n?.title||'')}" placeholder="e.g. Lecture 5 summary"></div><div class="field"><label>Subject</label><select id="suite-note-subject">${subjectOptions(n?.subjectId||'')}</select></div><div class="field"><label>Tags <span class="field-optional">comma separated</span></label><input id="suite-note-tags" value="${esc(n?.tags||'')}" placeholder="exam, formulas, revise"></div><div class="field"><label>Note</label><textarea id="suite-note-body" class="suite-big-textarea" placeholder="Write your note…">${esc(n?.body||'')}</textarea></div><div class="suite-sheet-actions">${n?'<button class="btn btn-danger" type="button" id="suite-note-delete">Delete</button>':'<span></span>'}<button class="btn btn-primary" type="submit">${n?'Save changes':'Create note'}</button></div></form>`);document.getElementById('suite-note-delete')?.addEventListener('click',()=>{if(confirm('Delete this note?')){v.notes=v.notes.filter(x=>x.id!==n.id);saveSuite(v);closeSheet();render();}});document.getElementById('suite-note-form').onsubmit=e=>{e.preventDefault();const payload={id:n?.id||uid('note'),title:document.getElementById('suite-note-title').value.trim(),subjectId:document.getElementById('suite-note-subject').value,tags:document.getElementById('suite-note-tags').value.trim(),body:document.getElementById('suite-note-body').value.trim(),pinned:n?.pinned||false,createdAt:n?.createdAt||now(),updatedAt:now()};if(!payload.title)return;if(n)Object.assign(n,payload);else v.notes.unshift(payload);logActivity(v,'note',`${n?'Updated':'Created'} note “${payload.title}”`,'subjects/Notes');saveSuite(v);closeSheet();render();};}

  function resourcesView(){const v=suite();return `<section class="suite-page">${pageHead('Subjects · Resources','Resources','Keep useful links, books, videos and reference material organized by subject.',`<button class="btn btn-primary" id="suite-add-resource">＋ Add resource</button>`)}${v.resources.length?`<div class="suite-resource-grid">${[...v.resources].sort((a,b)=>(b.favorite?1:0)-(a.favorite?1:0)||Number(b.createdAt)-Number(a.createdAt)).map(resourceCard).join('')}</div>`:empty('↗','No resources saved','Save a useful website, video, document reference, or book.',`<button class="btn btn-primary" id="suite-empty-resource">Add resource</button>`)}</section>`;}
  function resourceCard(r){return `<article class="suite-resource-card" data-resource-id="${esc(r.id)}"><div class="suite-resource-type"><span>${r.type==='video'?'▶':r.type==='book'?'▤':r.type==='document'?'□':'↗'}</span><small>${esc(r.type||'link')}</small><button data-resource-favorite="${esc(r.id)}">${r.favorite?'★':'☆'}</button></div><h2>${esc(r.title)}</h2><p>${esc(r.description||r.url||'Saved resource')}</p><footer><span>${esc(subjectName(r.subjectId))}</span><div><button data-resource-edit="${esc(r.id)}">Edit</button>${r.url?`<button class="primary" data-resource-open="${esc(r.id)}">Open ↗</button>`:''}</div></footer></article>`;}
  function bindResources(){bindSuiteRoutes();document.getElementById('suite-add-resource')?.addEventListener('click',()=>openResourceSheet());document.getElementById('suite-empty-resource')?.addEventListener('click',()=>openResourceSheet());document.querySelectorAll('[data-resource-edit]').forEach(b=>b.onclick=e=>{e.stopPropagation();openResourceSheet(b.dataset.resourceEdit);});document.querySelectorAll('[data-resource-favorite]').forEach(b=>b.onclick=e=>{e.stopPropagation();const v=suite(),r=v.resources.find(x=>x.id===b.dataset.resourceFavorite);if(r){r.favorite=!r.favorite;saveSuite(v);render();}});document.querySelectorAll('[data-resource-open]').forEach(b=>b.onclick=e=>{e.stopPropagation();const r=suite().resources.find(x=>x.id===b.dataset.resourceOpen),url=safeUrl(r?.url);if(url)window.open(url,'_blank','noopener,noreferrer');else showToast('This resource URL is invalid.');});}
  function openResourceSheet(id=''){const v=suite(),r=v.resources.find(x=>x.id===id);openSheet(r?'Edit resource':'Add resource',`<form id="suite-resource-form"><div class="field"><label>Title</label><input id="suite-resource-title" required maxlength="120" value="${esc(r?.title||'')}" placeholder="e.g. Calculus visual guide"></div><div class="suite-form-grid"><div class="field"><label>Subject</label><select id="suite-resource-subject">${subjectOptions(r?.subjectId||'')}</select></div><div class="field"><label>Type</label><select id="suite-resource-type"><option value="link" ${r?.type==='link'?'selected':''}>Link</option><option value="video" ${r?.type==='video'?'selected':''}>Video</option><option value="document" ${r?.type==='document'?'selected':''}>Document reference</option><option value="book" ${r?.type==='book'?'selected':''}>Book</option></select></div></div><div class="field"><label>URL <span class="field-optional">optional</span></label><input id="suite-resource-url" inputmode="url" value="${esc(r?.url||'')}" placeholder="https://…"></div><div class="field"><label>Description</label><textarea id="suite-resource-description" placeholder="Why is this useful?">${esc(r?.description||'')}</textarea></div><div class="suite-sheet-actions">${r?'<button class="btn btn-danger" type="button" id="suite-resource-delete">Delete</button>':'<span></span>'}<button class="btn btn-primary" type="submit">${r?'Save changes':'Add resource'}</button></div></form>`);document.getElementById('suite-resource-delete')?.addEventListener('click',()=>{if(confirm('Delete this resource?')){v.resources=v.resources.filter(x=>x.id!==r.id);saveSuite(v);closeSheet();render();}});document.getElementById('suite-resource-form').onsubmit=e=>{e.preventDefault();const payload={id:r?.id||uid('res'),title:document.getElementById('suite-resource-title').value.trim(),subjectId:document.getElementById('suite-resource-subject').value,type:document.getElementById('suite-resource-type').value,url:document.getElementById('suite-resource-url').value.trim(),description:document.getElementById('suite-resource-description').value.trim(),favorite:r?.favorite||false,createdAt:r?.createdAt||now(),updatedAt:now()};if(!payload.title)return;if(payload.url&&!safeUrl(payload.url)){showToast('Enter a valid web address or leave the URL empty.');return;}if(r)Object.assign(r,payload);else v.resources.unshift(payload);logActivity(v,'resource',`${r?'Updated':'Saved'} resource “${payload.title}”`,'subjects/Resources');saveSuite(v);closeSheet();render();};}

  function assignmentsView(){const v=suite();const list=[...v.assignments].sort((a,b)=>(a.status==='done')-(b.status==='done')||String(a.dueDate||'9999').localeCompare(String(b.dueDate||'9999'))).filter(a=>ui.assignmentFilter==='all'||a.status===ui.assignmentFilter);return `<section class="suite-page">${pageHead('Subjects · Assignments','Assignments','Track coursework from first task to submission. Due dates automatically appear in Calendar → Deadlines.',`<button class="btn btn-primary" id="suite-add-assignment">＋ New assignment</button>`)}<div class="suite-filterbar">${[['all','All'],['todo','To do'],['doing','In progress'],['done','Done']].map(([x,l])=>`<button class="${ui.assignmentFilter===x?'active':''}" data-assignment-filter="${x}">${l}</button>`).join('')}</div>${list.length?`<div class="suite-assignment-list">${list.map(assignmentCard).join('')}</div>`:empty('✓','No assignments here',ui.assignmentFilter==='all'?'Add coursework and give it a due date.':'This filter is clear.',`<button class="btn btn-primary" id="suite-empty-assignment">New assignment</button>`)}</section>`;}
  function assignmentCard(a){const overdue=a.dueDate&&new Date(`${a.dueDate}T23:59:59`)<new Date()&&a.status!=='done';return `<article class="suite-assignment ${a.status==='done'?'done':''} ${overdue?'overdue':''}" data-assignment-id="${esc(a.id)}"><button class="suite-check" data-assignment-toggle="${esc(a.id)}" aria-label="Toggle complete">${a.status==='done'?'✓':''}</button><div class="suite-assignment-copy"><div><span class="suite-priority ${esc(a.priority||'medium')}">${esc(a.priority||'medium')}</span><small>${esc(subjectName(a.subjectId))}</small></div><h2>${esc(a.title)}</h2><p>${esc(a.notes||'No extra notes.')}</p></div><div class="suite-assignment-meta"><strong>${a.dueDate?fmtDate(a.dueDate):'No due date'}</strong><small>${a.dueDate?relativeDate(a.dueDate):prettify(a.status)}</small><button data-assignment-edit="${esc(a.id)}">Edit</button></div></article>`;}
  function bindAssignments(){bindSuiteRoutes();document.getElementById('suite-add-assignment')?.addEventListener('click',()=>openAssignmentSheet());document.getElementById('suite-empty-assignment')?.addEventListener('click',()=>openAssignmentSheet());document.querySelectorAll('[data-assignment-filter]').forEach(b=>b.onclick=()=>{ui.assignmentFilter=b.dataset.assignmentFilter;render();});document.querySelectorAll('[data-assignment-edit]').forEach(b=>b.onclick=()=>openAssignmentSheet(b.dataset.assignmentEdit));document.querySelectorAll('[data-assignment-toggle]').forEach(b=>b.onclick=()=>toggleAssignment(b.dataset.assignmentToggle));}
  function toggleAssignment(id){const v=suite(),a=v.assignments.find(x=>x.id===id);if(!a)return;a.status=a.status==='done'?'todo':'done';a.completedAt=a.status==='done'?now():null;logActivity(v,'assignment',`${a.status==='done'?'Completed':'Reopened'} “${a.title}”`,'subjects/Assignments');saveSuite(v);render();}
  function openAssignmentSheet(id=''){const v=suite(),a=v.assignments.find(x=>x.id===id);openSheet(a?'Edit assignment':'New assignment',`<form id="suite-assignment-form"><div class="field"><label>Assignment</label><input id="suite-assignment-title" required maxlength="140" value="${esc(a?.title||'')}" placeholder="e.g. Problem set 4"></div><div class="suite-form-grid"><div class="field"><label>Subject</label><select id="suite-assignment-subject">${subjectOptions(a?.subjectId||'')}</select></div><div class="field"><label>Due date</label><input id="suite-assignment-due" type="date" value="${esc(a?.dueDate||'')}"></div></div><div class="suite-form-grid"><div class="field"><label>Priority</label><select id="suite-assignment-priority"><option value="low" ${a?.priority==='low'?'selected':''}>Low</option><option value="medium" ${!a||a.priority==='medium'?'selected':''}>Medium</option><option value="high" ${a?.priority==='high'?'selected':''}>High</option></select></div><div class="field"><label>Status</label><select id="suite-assignment-status"><option value="todo" ${!a||a.status==='todo'?'selected':''}>To do</option><option value="doing" ${a?.status==='doing'?'selected':''}>In progress</option><option value="done" ${a?.status==='done'?'selected':''}>Done</option></select></div></div><div class="field"><label>Notes</label><textarea id="suite-assignment-notes" placeholder="Requirements, submission link, checklist…">${esc(a?.notes||'')}</textarea></div><div class="suite-sheet-actions">${a?'<button class="btn btn-danger" type="button" id="suite-assignment-delete">Delete</button>':'<span></span>'}<button class="btn btn-primary" type="submit">${a?'Save changes':'Create assignment'}</button></div></form>`);document.getElementById('suite-assignment-delete')?.addEventListener('click',()=>{if(confirm('Delete this assignment?')){v.assignments=v.assignments.filter(x=>x.id!==a.id);saveSuite(v);closeSheet();render();}});document.getElementById('suite-assignment-form').onsubmit=e=>{e.preventDefault();const status=document.getElementById('suite-assignment-status').value;const payload={id:a?.id||uid('asg'),title:document.getElementById('suite-assignment-title').value.trim(),subjectId:document.getElementById('suite-assignment-subject').value,dueDate:document.getElementById('suite-assignment-due').value,priority:document.getElementById('suite-assignment-priority').value,status,notes:document.getElementById('suite-assignment-notes').value.trim(),createdAt:a?.createdAt||now(),updatedAt:now(),completedAt:status==='done'?(a?.completedAt||now()):null};if(!payload.title)return;if(a)Object.assign(a,payload);else v.assignments.unshift(payload);logActivity(v,'assignment',`${a?'Updated':'Created'} assignment “${payload.title}”`,'subjects/Assignments');saveSuite(v);closeSheet();render();};}

  function deadlineItems(v){
    const assignment=v.assignments.filter(a=>a.dueDate).map(a=>({id:a.id,source:'assignment',title:a.title,date:a.dueDate,subjectId:a.subjectId,done:a.status==='done',detail:`Assignment · ${prettify(a.priority||'medium')} priority`}));
    const custom=v.deadlines.map(d=>({...d,source:'custom'}));
    const exam=exams().filter(e=>e.day).map(e=>({id:e.id,source:'exam',title:e.subject||subjectName(e.subjectId),date:normalizeExamDate(e.day),subjectId:e.subjectId,done:false,detail:`Exam · ${e.day}${e.time?` · ${e.time}`:''}${e.location?` · ${e.location}`:''}`}));
    return [...assignment,...custom,...exam].sort((a,b)=>String(a.date||'9999').localeCompare(String(b.date||'9999')));
  }
  function normalizeExamDate(day){if(/^\d{4}-\d{2}-\d{2}$/.test(String(day)))return String(day);return '';}
  function deadlineRow(d){const overdue=d.date&&new Date(`${d.date}T23:59:59`)<new Date()&&!d.done;return `<button class="suite-row suite-deadline-row ${d.done?'done':''} ${overdue?'overdue':''}" data-deadline-source="${esc(d.source)}" data-deadline-id="${esc(d.id)}"><span class="suite-row-icon">${d.source==='exam'?'%':d.source==='assignment'?'✓':'!'}</span><span><strong>${esc(d.title)}</strong><small>${esc(d.detail||subjectName(d.subjectId))}</small></span><time><b>${esc(d.date?fmtDate(d.date):'Undated')}</b><small>${esc(d.date?relativeDate(d.date):'Open exam schedule')}</small></time></button>`;}
  function deadlinesView(){const v=suite();let items=deadlineItems(v);if(ui.deadlineFilter==='upcoming')items=items.filter(d=>!d.done&&(!d.date||new Date(`${d.date}T23:59:59`)>=new Date()));if(ui.deadlineFilter==='overdue')items=items.filter(d=>!d.done&&d.date&&new Date(`${d.date}T23:59:59`)<new Date());if(ui.deadlineFilter==='done')items=items.filter(d=>d.done);return `<section class="suite-page">${pageHead('Calendar · Deadlines','Deadlines','Assignments and exams appear automatically. Add standalone academic deadlines for everything else.',`<button class="btn btn-primary" id="suite-add-deadline">＋ Add deadline</button>`)}<div class="suite-filterbar">${[['upcoming','Upcoming'],['overdue','Overdue'],['done','Completed'],['all','All']].map(([x,l])=>`<button class="${ui.deadlineFilter===x?'active':''}" data-deadline-filter="${x}">${l}</button>`).join('')}</div>${items.length?`<div class="suite-deadline-timeline">${items.map(deadlineRow).join('')}</div>`:empty('□','Nothing in this view','Deadlines from assignments and exams will collect here automatically.')}</section>`;}
  function bindDeadlines(){bindSuiteRoutes();document.getElementById('suite-add-deadline')?.addEventListener('click',()=>openDeadlineSheet());document.querySelectorAll('[data-deadline-filter]').forEach(b=>b.onclick=()=>{ui.deadlineFilter=b.dataset.deadlineFilter;render();});document.querySelectorAll('[data-deadline-source]').forEach(b=>b.onclick=()=>{const src=b.dataset.deadlineSource,id=b.dataset.deadlineId;if(src==='assignment')openAssignmentSheet(id);else if(src==='custom')openDeadlineSheet(id);else setHash('calendar/Exams');});}
  function openDeadlineSheet(id=''){const v=suite(),d=v.deadlines.find(x=>x.id===id);openSheet(d?'Edit deadline':'Add deadline',`<form id="suite-deadline-form"><div class="field"><label>Deadline</label><input id="suite-deadline-title" required maxlength="140" value="${esc(d?.title||'')}" placeholder="e.g. Registration closes"></div><div class="suite-form-grid"><div class="field"><label>Date</label><input id="suite-deadline-date" required type="date" value="${esc(d?.date||'')}"></div><div class="field"><label>Subject</label><select id="suite-deadline-subject">${subjectOptions(d?.subjectId||'')}</select></div></div><div class="field"><label>Details</label><textarea id="suite-deadline-detail" placeholder="What needs to happen before this date?">${esc(d?.detail||'')}</textarea></div><label class="suite-inline-check"><input id="suite-deadline-done" type="checkbox" ${d?.done?'checked':''}> Mark as completed</label><div class="suite-sheet-actions">${d?'<button class="btn btn-danger" type="button" id="suite-deadline-delete">Delete</button>':'<span></span>'}<button class="btn btn-primary" type="submit">${d?'Save changes':'Add deadline'}</button></div></form>`);document.getElementById('suite-deadline-delete')?.addEventListener('click',()=>{if(confirm('Delete this deadline?')){v.deadlines=v.deadlines.filter(x=>x.id!==d.id);saveSuite(v);closeSheet();render();}});document.getElementById('suite-deadline-form').onsubmit=e=>{e.preventDefault();const payload={id:d?.id||uid('ddl'),title:document.getElementById('suite-deadline-title').value.trim(),date:document.getElementById('suite-deadline-date').value,subjectId:document.getElementById('suite-deadline-subject').value,detail:document.getElementById('suite-deadline-detail').value.trim(),done:document.getElementById('suite-deadline-done').checked,createdAt:d?.createdAt||now()};if(d)Object.assign(d,payload);else v.deadlines.push(payload);logActivity(v,'deadline',`${d?'Updated':'Added'} deadline “${payload.title}”`,'calendar/Deadlines');saveSuite(v);closeSheet();render();};}

  function profileView(){const v=suite(),p=v.profile;return `<section class="suite-page">${pageHead('Account','Profile','Keep your student identity and study goals in one place.',`<button class="btn btn-primary" id="suite-edit-profile">Edit profile</button>`)}<div class="suite-profile-grid"><article class="suite-profile-card"><div class="suite-profile-avatar">${esc((p.name||'S').slice(0,1).toUpperCase())}</div><h2>${esc(p.name||'Student')}</h2><p>@${esc(p.username||'student')}</p><div class="suite-profile-tags"><span>${esc(p.course||'General studies')}</span>${p.semester?`<span>${esc(p.semester)}</span>`:''}</div><blockquote>${esc(p.bio||'Add a short bio about what you are studying and working toward.')}</blockquote></article><article class="suite-panel"><div class="suite-panel-head"><div><span class="eyebrow">Academic identity</span><h2>Study details</h2></div></div><dl class="suite-details"><div><dt>School / university</dt><dd>${esc(p.school||'Not set')}</dd></div><div><dt>Course</dt><dd>${esc(p.course||'General studies')}</dd></div><div><dt>Semester / year</dt><dd>${esc(p.semester||'Not set')}</dd></div><div><dt>Weekly focus target</dt><dd>${esc(p.targetHours||8)} hours</dd></div><div><dt>Study language</dt><dd>${esc(p.studyLanguage||'English')}</dd></div></dl></article><article class="suite-panel suite-profile-links"><div class="suite-panel-head"><div><span class="eyebrow">Connected</span><h2>Your workspace</h2></div></div><div class="suite-shortcuts"><button data-suite-go="subjects/All%20subjects"><span>◇</span><strong>${subjects().length} subjects</strong><small>Academic library</small></button><button data-suite-go="dashboard/Progress"><span>◷</span><strong>${v.focusLog.length} focus sessions</strong><small>Study history</small></button><button data-suite-go="subjects/Assignments"><span>✓</span><strong>${v.assignments.length} assignments</strong><small>Coursework tracker</small></button><button data-suite-go="study-rooms/My%20study%20rooms"><span>◎</span><strong>My study rooms</strong><small>Community workspace</small></button></div></article></div></section>`;}
  function bindProfile(){bindSuiteRoutes();document.getElementById('suite-edit-profile')?.addEventListener('click',openProfileSheet);}
  function openProfileSheet(){const v=suite(),p=v.profile;openSheet('Edit profile',`<form id="suite-profile-form"><div class="suite-form-grid"><div class="field"><label>Name</label><input id="suite-profile-name" required value="${esc(p.name)}"></div><div class="field"><label>Username</label><input id="suite-profile-username" value="${esc(p.username)}"></div></div><div class="field"><label>School / university</label><input id="suite-profile-school" value="${esc(p.school)}" placeholder="Optional"></div><div class="suite-form-grid"><div class="field"><label>Course</label><input id="suite-profile-course" value="${esc(p.course)}"></div><div class="field"><label>Semester / year</label><input id="suite-profile-semester" value="${esc(p.semester)}"></div></div><div class="field"><label>Bio</label><textarea id="suite-profile-bio" maxlength="360">${esc(p.bio)}</textarea></div><div class="field"><label>Weekly focus target (hours)</label><input id="suite-profile-target" type="number" min="1" max="80" value="${esc(p.targetHours||8)}"></div><button class="btn btn-primary auth-submit" type="submit">Save profile</button></form>`);document.getElementById('suite-profile-form').onsubmit=e=>{e.preventDefault();Object.assign(p,{name:document.getElementById('suite-profile-name').value.trim(),username:document.getElementById('suite-profile-username').value.trim(),school:document.getElementById('suite-profile-school').value.trim(),course:document.getElementById('suite-profile-course').value.trim(),semester:document.getElementById('suite-profile-semester').value.trim(),bio:document.getElementById('suite-profile-bio').value.trim(),targetHours:Number(document.getElementById('suite-profile-target').value)||8});logActivity(v,'profile','Updated profile','profile');saveSuite(v);closeSheet();render();};}

  function settingsView(){const v=suite(),p=v.preferences;return `<section class="suite-page">${pageHead('Workspace','Settings','Tune the workspace around how you study. Preferences stay on this browser.',`<button class="btn btn-ghost" id="suite-export">⇩ Export data</button><label class="btn btn-ghost suite-import">⇧ Import<input id="suite-import-file" type="file" accept="application/json" hidden></label>`)}<div class="suite-settings-grid"><article class="suite-setting-card"><span class="suite-setting-icon">◐</span><div><h2>Appearance</h2><p>Choose a theme and interface density.</p></div><div class="suite-segment"><button data-theme-choice="light" class="${document.documentElement.dataset.theme!=='dark'?'active':''}">Light</button><button data-theme-choice="dark" class="${document.documentElement.dataset.theme==='dark'?'active':''}">Dark</button></div><select id="suite-density"><option value="comfortable" ${p.density==='comfortable'?'selected':''}>Comfortable density</option><option value="compact" ${p.density==='compact'?'selected':''}>Compact density</option></select></article><article class="suite-setting-card"><span class="suite-setting-icon">✦</span><div><h2>Motion</h2><p>Control interface animation independently from your system preference.</p></div><div class="suite-segment"><button data-motion-choice="full" class="${p.motion==='full'?'active':''}">Full</button><button data-motion-choice="reduced" class="${p.motion==='reduced'?'active':''}">Reduced</button></div></article><article class="suite-setting-card"><span class="suite-setting-icon">◷</span><div><h2>Study defaults</h2><p>Set a default focus block and week start.</p></div><div class="suite-form-grid"><select id="suite-focus-default">${[25,45,50,60,90,120].map(x=>`<option value="${x}" ${Number(p.defaultFocus)===x?'selected':''}>${x} min focus</option>`).join('')}</select><select id="suite-week-start">${['Sunday','Monday','Saturday'].map(x=>`<option ${p.weekStarts===x?'selected':''}>${x}</option>`).join('')}</select></div></article><article class="suite-setting-card danger"><span class="suite-setting-icon">↻</span><div><h2>Local data tools</h2><p>Export first if you may want this data later.</p></div><button class="btn btn-danger" id="suite-reset-suite">Reset notes, tasks & progress</button></article></div><p class="suite-privacy-note">Dafatii currently stores these workspace settings and student-suite records in this browser. Chat, calendar, subjects and study-room data have their own existing local stores and are not erased by the suite reset.</p></section>`;}
  function bindSettings(){document.querySelectorAll('[data-theme-choice]').forEach(b=>b.onclick=()=>setTheme(b.dataset.themeChoice));document.querySelectorAll('[data-motion-choice]').forEach(b=>b.onclick=()=>{const v=suite();v.preferences.motion=b.dataset.motionChoice;saveSuite(v);syncSuitePreferences();render();});document.getElementById('suite-density')?.addEventListener('change',e=>{const v=suite();v.preferences.density=e.target.value;saveSuite(v);syncSuitePreferences();});document.getElementById('suite-focus-default')?.addEventListener('change',e=>{const v=suite();v.preferences.defaultFocus=Number(e.target.value);saveSuite(v);});document.getElementById('suite-week-start')?.addEventListener('change',e=>{const v=suite();v.preferences.weekStarts=e.target.value;saveSuite(v);});document.getElementById('suite-export')?.addEventListener('click',exportData);document.getElementById('suite-import-file')?.addEventListener('change',importData);document.getElementById('suite-reset-suite')?.addEventListener('click',()=>{if(confirm('Reset notes, resources, assignments, deadlines, focus history, application trackers, and profile preferences?')){localStorage.removeItem(SUITE_KEY);render();}});}
  function setTheme(theme){document.documentElement.dataset.theme=theme;window.DafatiiData.writeString('dafatii:theme',theme);document.documentElement.style.colorScheme=theme;document.querySelector('meta[name="theme-color"]')?.setAttribute('content',theme==='dark'?'#07111f':'#f5f8ff');render();}
  function exportData(){const data={exportedAt:new Date().toISOString(),suite:suite(),subjects:state.subjects,lectures:state.lectures,schedule:readJSON(SCHEDULE_KEY,[]),exams:exams(),rooms:roomState(),chat:chatState()};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`dafatii-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);}
  async function importData(e){const file=e.target.files?.[0];if(!file)return;try{const data=JSON.parse(await file.text());if(!data||typeof data!=='object')throw new Error('Invalid file');if(!confirm('Import this Dafatii backup into this browser? Existing local data in included sections will be replaced.'))return;if(data.suite)writeJSON(SUITE_KEY,data.suite);if(Array.isArray(data.subjects)){state.subjects=data.subjects;saveSubjects();}if(data.lectures&&typeof data.lectures==='object'){state.lectures=data.lectures;saveLectures();}if(Array.isArray(data.schedule))writeJSON(SCHEDULE_KEY,data.schedule);if(Array.isArray(data.exams))writeJSON(EXAMS_KEY,data.exams);if(data.rooms)writeJSON(ROOM_KEY,data.rooms);if(data.chat)writeJSON(CHAT_KEY,data.chat);showToast('Backup imported');render();}catch{showToast('Could not read this backup file.');}finally{e.target.value='';}}
  function syncSuitePreferences(){const p=suite().preferences;document.documentElement.dataset.density=p.density;document.documentElement.dataset.motion=p.motion;}

  function courseView(){const v=suite(),p=v.profile;return `<section class="suite-page">${pageHead('Settings · Course','Course setup','Update your academic direction and optionally seed a useful starter subject set.',`<button class="btn btn-primary" id="suite-course-edit">Edit course details</button>`)}<div class="suite-course-hero"><div><span class="eyebrow">Current course</span><h2>${esc(p.course||'General studies')}</h2><p>${esc(p.school||'No institution set')}${p.semester?` · ${esc(p.semester)}`:''}</p></div><div><strong>${subjects().length}</strong><span>active subjects</span></div></div><div class="suite-template-grid">${Object.entries(COURSE_TEMPLATES).map(([name,list])=>`<article class="suite-template-card"><span>◇</span><h2>${esc(name)}</h2><p>${esc(list.join(' · '))}</p><button class="btn btn-ghost" data-course-template="${esc(name)}">Add subject template</button></article>`).join('')}</div><p class="suite-privacy-note">Templates only add missing subjects. They never delete your existing subjects, lectures, calendar entries, or grades.</p></section>`;}
  function bindCourse(){document.getElementById('suite-course-edit')?.addEventListener('click',openProfileSheet);document.querySelectorAll('[data-course-template]').forEach(b=>b.onclick=()=>applyCourseTemplate(b.dataset.courseTemplate));}
  function applyCourseTemplate(name){const list=COURSE_TEMPLATES[name];if(!list)return;const existing=new Set(subjects().map(s=>s.name.toLowerCase()));const additions=list.filter(n=>!existing.has(n.toLowerCase())).map(n=>({id:uid('subject'),name:n,icon:'◇'}));if(!additions.length){showToast('All template subjects are already present.');return;}if(!confirm(`Add ${additions.length} missing subjects from the ${name} template?`))return;state.subjects.push(...additions);saveSubjects();const v=suite();v.profile.course=name;logActivity(v,'course',`Applied ${name} subject template`,'change-course');saveSuite(v);render();}

  function languageView(){const v=suite(),p=v.profile;const langs=['English','Arabic','Kurdish','French','Spanish','German','Turkish'];return `<section class="suite-page">${pageHead('Settings · Language','Language preferences','Choose the language you study in and the interface reading direction you prefer.')}<div class="suite-language-grid"><article class="suite-panel"><div class="suite-panel-head"><div><span class="eyebrow">Study content</span><h2>Primary study language</h2></div></div><p class="muted">Used as a profile preference for notes, study rooms and future content recommendations.</p><div class="suite-language-options">${langs.map(l=>`<button data-study-language="${esc(l)}" class="${p.studyLanguage===l?'active':''}">${esc(l)}</button>`).join('')}</div></article><article class="suite-panel"><div class="suite-panel-head"><div><span class="eyebrow">Interface</span><h2>Reading direction</h2></div></div><p class="muted">Dafatii’s current interface copy is English. You can still switch page direction for Arabic/Kurdish study workflows without pretending the full product has been translated.</p><div class="suite-segment wide"><button data-direction="ltr" class="${document.documentElement.dir!=='rtl'?'active':''}">Left → right</button><button data-direction="rtl" class="${document.documentElement.dir==='rtl'?'active':''}">Right → left</button></div></article></div></section>`;}
  function bindLanguage(){document.querySelectorAll('[data-study-language]').forEach(b=>b.onclick=()=>{const v=suite();v.profile.studyLanguage=b.dataset.studyLanguage;saveSuite(v);render();});document.querySelectorAll('[data-direction]').forEach(b=>b.onclick=()=>{document.documentElement.dir=b.dataset.direction;window.DafatiiData.writeString('dafatii:direction',b.dataset.direction);render();});}

  function opportunityShell(kind,title,copy,seeds,records){const applied=new Set(records.map(x=>x.id));return `<section class="suite-page">${pageHead('Opportunities',title,copy)}<div class="suite-opportunity-grid">${seeds.map(o=>`<article class="suite-opportunity-card"><div class="suite-opportunity-top"><span>${kind==='work'?'↗':kind==='scholarship'?'✦':'♡'}</span><div>${(o.tags||[]).map(t=>`<i>${esc(t)}</i>`).join('')}</div></div><h2>${esc(o.title)}</h2><strong>${esc(o.org||o.amount||'Student opportunity')}</strong><p>${esc(o.summary)}</p>${o.deadline?`<small>Deadline ${fmtDate(o.deadline)} · ${relativeDate(o.deadline)}</small>`:''}${o.fit?`<small>${esc(o.fit)}</small>`:''}${o.mode?`<small>${esc(o.mode)}</small>`:''}${o.commitment?`<small>${esc(o.commitment)}</small>`:''}<button class="btn ${applied.has(o.id)?'btn-ghost':'btn-primary'}" data-opportunity="${kind}" data-opportunity-id="${esc(o.id)}">${applied.has(o.id)?'✓ In tracker':'Add to tracker'}</button></article>`).join('')}</div>${records.length?`<article class="suite-panel suite-tracker"><div class="suite-panel-head"><div><span class="eyebrow">My tracker</span><h2>${records.length} saved</h2></div></div><div class="suite-list">${records.map(r=>`<div class="suite-tracker-row"><span>${esc(r.title)}</span><select data-tracker-kind="${kind}" data-tracker-id="${esc(r.id)}"><option value="saved" ${r.status==='saved'?'selected':''}>Saved</option><option value="preparing" ${r.status==='preparing'?'selected':''}>Preparing</option><option value="applied" ${r.status==='applied'?'selected':''}>Applied</option><option value="closed" ${r.status==='closed'?'selected':''}>Closed</option></select><button data-tracker-remove="${kind}" data-tracker-id="${esc(r.id)}">×</button></div>`).join('')}</div></article>`:''}</section>`;}
  function workView(){const v=suite();return opportunityShell('work','Student work','A lightweight application tracker for flexible student roles. These are prototype examples—not live job listings.',WORK_SEEDS,v.applications);}
  function scholarshipView(){const v=suite();return opportunityShell('scholarship','Scholarships','Organize scholarship opportunities and application status. Example opportunities are clearly local prototype content.',SCHOLARSHIP_SEEDS,v.scholarships);}
  function volunteerView(){const v=suite(),tracked=new Set(v.volunteer.map(x=>x.id)),hours=v.support.filter(x=>x.type==='volunteer-hours').reduce((sum,x)=>sum+Number(x.hours||0),0);return `<section class="suite-page">${pageHead('Opportunities','Volunteer','Find a useful role, track your involvement, and log verified or self-reported service hours.',`<button class="btn btn-primary" id="suite-log-volunteer">＋ Log volunteer hours</button>`)}<div class="suite-metrics">${metric('♡',v.volunteer.length,'opportunities tracked')}${metric('◷',`${hours}h`,'service hours logged')}${metric('✓',v.volunteer.filter(x=>x.status==='applied').length,'active / applied')}${metric('◇',VOLUNTEER_SEEDS.length,'example roles available')}</div><div class="suite-opportunity-grid">${VOLUNTEER_SEEDS.map(o=>`<article class="suite-opportunity-card"><div class="suite-opportunity-top"><span>♡</span></div><h2>${esc(o.title)}</h2><strong>${esc(o.org)}</strong><p>${esc(o.summary)}</p><small>${esc(o.commitment)}</small><button class="btn ${tracked.has(o.id)?'btn-ghost':'btn-primary'}" data-opportunity="volunteer" data-opportunity-id="${esc(o.id)}">${tracked.has(o.id)?'✓ In tracker':'Add to tracker'}</button></article>`).join('')}</div>${v.volunteer.length?`<article class="suite-panel suite-tracker"><div class="suite-panel-head"><div><span class="eyebrow">My tracker</span><h2>${v.volunteer.length} saved</h2></div></div><div class="suite-list">${v.volunteer.map(r=>`<div class="suite-tracker-row"><span>${esc(r.title)}</span><select data-tracker-kind="volunteer" data-tracker-id="${esc(r.id)}"><option value="saved" ${r.status==='saved'?'selected':''}>Saved</option><option value="preparing" ${r.status==='preparing'?'selected':''}>Contacting</option><option value="applied" ${r.status==='applied'?'selected':''}>Active / applied</option><option value="closed" ${r.status==='closed'?'selected':''}>Completed</option></select><button data-tracker-remove="volunteer" data-tracker-id="${esc(r.id)}">×</button></div>`).join('')}</div></article>`:''}</section>`;}
  function bindWork(){bindOpportunity('work');}
  function bindScholarships(){bindOpportunity('scholarship');}
  function bindVolunteer(){bindOpportunity('volunteer');document.getElementById('suite-log-volunteer')?.addEventListener('click',openVolunteerLogSheet);}
  function recordSet(v,kind){return kind==='work'?v.applications:kind==='scholarship'?v.scholarships:v.volunteer;}
  function seedSet(kind){return kind==='work'?WORK_SEEDS:kind==='scholarship'?SCHOLARSHIP_SEEDS:VOLUNTEER_SEEDS;}
  function bindOpportunity(kind){document.querySelectorAll(`[data-opportunity="${kind}"]`).forEach(b=>b.onclick=()=>{const v=suite(),records=recordSet(v,kind),seed=seedSet(kind).find(x=>x.id===b.dataset.opportunityId);if(!seed)return;const existing=records.find(x=>x.id===seed.id);if(existing){showToast('Already in your tracker.');return;}records.push({id:seed.id,title:seed.title,status:'saved',addedAt:now()});logActivity(v,kind,`Saved “${seed.title}”`);saveSuite(v);render();});document.querySelectorAll(`[data-tracker-kind="${kind}"]`).forEach(s=>s.onchange=()=>{const v=suite(),r=recordSet(v,kind).find(x=>x.id===s.dataset.trackerId);if(r){r.status=s.value;saveSuite(v);}});document.querySelectorAll(`[data-tracker-remove="${kind}"]`).forEach(b=>b.onclick=()=>{const v=suite();if(kind==='work')v.applications=v.applications.filter(x=>x.id!==b.dataset.trackerId);if(kind==='scholarship')v.scholarships=v.scholarships.filter(x=>x.id!==b.dataset.trackerId);if(kind==='volunteer')v.volunteer=v.volunteer.filter(x=>x.id!==b.dataset.trackerId);saveSuite(v);render();});}
  function openVolunteerLogSheet(){const v=suite();openSheet('Log volunteer hours',`<form id="suite-vol-hours-form"><div class="field"><label>Activity</label><input id="suite-vol-label" required placeholder="e.g. STEM outreach event"></div><div class="suite-form-grid"><div class="field"><label>Hours</label><input id="suite-vol-hours" required type="number" min="0.25" step="0.25" value="2"></div><div class="field"><label>Date</label><input id="suite-vol-date" type="date" value="${new Date().toISOString().slice(0,10)}"></div></div><button class="btn btn-primary auth-submit" type="submit">Log hours</button></form>`);document.getElementById('suite-vol-hours-form').onsubmit=e=>{e.preventDefault();const label=document.getElementById('suite-vol-label').value.trim(),hours=Number(document.getElementById('suite-vol-hours').value);if(!label||!hours)return;v.support.push({id:uid('volhours'),type:'volunteer-hours',label,hours,date:document.getElementById('suite-vol-date').value,at:now()});logActivity(v,'volunteer',`Logged ${hours} volunteer hours`,'volunteer');saveSuite(v);closeSheet();render();};}

  function supportView(){const v=suite();return `<section class="suite-page">${pageHead('Support Dafatii','Support the project','This prototype does not connect to payments. You can still record feedback, sponsorship interest, or non-financial support without a fake checkout.')}<div class="suite-support-grid"><article class="suite-support-card"><span>✎</span><h2>Send product feedback</h2><p>Capture a feature request, bug report or idea for the team.</p><button class="btn btn-primary" data-support-kind="feedback">Write feedback</button></article><article class="suite-support-card"><span>↗</span><h2>Sponsorship interest</h2><p>Record interest from a school, club or organization. No payment is processed.</p><button class="btn btn-ghost" data-support-kind="sponsor">Record interest</button></article><article class="suite-support-card"><span>♡</span><h2>Community contribution</h2><p>Note how you want to contribute: design, translation, mentoring, content or testing.</p><button class="btn btn-ghost" data-support-kind="community">Add contribution</button></article></div>${v.support.filter(x=>x.type!=='volunteer-hours').length?`<article class="suite-panel"><div class="suite-panel-head"><div><span class="eyebrow">Saved locally</span><h2>Your support notes</h2></div></div><div class="suite-list">${v.support.filter(x=>x.type!=='volunteer-hours').map(x=>`<div class="suite-support-note"><span>${esc(prettify(x.type))}</span><strong>${esc(x.title||x.name||'Contribution')}</strong><p>${esc(x.message||x.detail||'')}</p><small>${relativeTime(x.at)}</small></div>`).join('')}</div></article>`:''}</section>`;}
  function bindSupport(){document.querySelectorAll('[data-support-kind]').forEach(b=>b.onclick=()=>openSupportSheet(b.dataset.supportKind));}
  function openSupportSheet(kind){const titles={feedback:'Product feedback',sponsor:'Sponsorship interest',community:'Community contribution'};openSheet(titles[kind],`<form id="suite-support-form"><div class="field"><label>${kind==='sponsor'?'Organization / contact':'Title'}</label><input id="suite-support-title" required maxlength="140" placeholder="${kind==='feedback'?'e.g. Improve exam revision flow':kind==='sponsor'?'e.g. Student club':'e.g. Arabic translation'}"></div><div class="field"><label>Details</label><textarea id="suite-support-message" class="suite-big-textarea" required placeholder="Add the details here…"></textarea></div><button class="btn btn-primary auth-submit" type="submit">Save locally</button></form>`);document.getElementById('suite-support-form').onsubmit=e=>{e.preventDefault();const v=suite();v.support.unshift({id:uid('sup'),type:kind,title:document.getElementById('suite-support-title').value.trim(),message:document.getElementById('suite-support-message').value.trim(),at:now()});saveSuite(v);closeSheet();render();};}

  function openFocusSheet(){const v=suite(),def=v.preferences.defaultFocus||50;openSheet('Log study session',`<form id="suite-focus-form"><div class="field"><label>Session label</label><input id="suite-focus-label" required value="Focused study" placeholder="e.g. Calculus revision"></div><div class="suite-form-grid"><div class="field"><label>Minutes</label><input id="suite-focus-minutes" type="number" min="5" max="720" value="${esc(def)}" required></div><div class="field"><label>Subject</label><select id="suite-focus-subject">${subjectOptions('')}</select></div></div><button class="btn btn-primary auth-submit" type="submit">Add to progress</button></form>`);document.getElementById('suite-focus-form').onsubmit=e=>{e.preventDefault();const minutes=Number(document.getElementById('suite-focus-minutes').value),label=document.getElementById('suite-focus-label').value.trim();if(!minutes||!label)return;v.focusLog.unshift({id:uid('focus'),minutes,label,subjectId:document.getElementById('suite-focus-subject').value,at:now()});logActivity(v,'focus',`Logged ${minutes} minutes of focus`,'dashboard/Progress');saveSuite(v);closeSheet();render();};}

  function openSheet(title,body){const root=document.getElementById('overlay-root');if(!root)return;root.innerHTML=`<div class="entity-sheet-overlay suite-overlay" id="suite-overlay"><section class="entity-sheet suite-sheet" role="dialog" aria-modal="true" aria-label="${esc(title)}"><div class="entity-sheet-handle"></div><div class="entity-sheet-head"><div><div class="eyebrow">Dafatii</div><h2>${esc(title)}</h2></div><button class="icon-btn" id="suite-sheet-close" aria-label="Close">×</button></div>${body}</section></div>`;document.getElementById('suite-sheet-close').onclick=closeSheet;document.getElementById('suite-overlay').onclick=e=>{if(e.target.id==='suite-overlay')closeSheet();};setTimeout(()=>document.querySelector('.suite-sheet input:not([type="checkbox"]),.suite-sheet textarea')?.focus(),40);}
  function closeSheet(){const root=document.getElementById('overlay-root');if(root)root.innerHTML='';}
  function bindSuiteRoutes(){document.querySelectorAll('[data-suite-go]').forEach(b=>b.onclick=()=>setHash(b.dataset.suiteGo));bindMaterialOpeners();}

  const storedDir=window.DafatiiData.readString('dafatii:direction');if(storedDir==='rtl'||storedDir==='ltr')document.documentElement.dir=storedDir;
  syncSuitePreferences();
})();