const fs=require('node:fs');const assert=require('node:assert/strict');
const backend=fs.readFileSync('functions/_lib/admin-supervision.mjs','utf8');
const routes=fs.readFileSync('functions/_lib/dafaa-routes.mjs','utf8');
const router=fs.readFileSync('functions/api/v1/[[path]].js','utf8');
const auth=fs.readFileSync('functions/_lib/auth.mjs','utf8');
const profile=fs.readFileSync('functions/_lib/school-signup-profile.mjs','utf8');
const ui=fs.readFileSync('admin-supervision.js','utf8');
const dafaUi=fs.readFileSync('dafaa-ui.js','utf8');
const index=fs.readFileSync('index.html','utf8');
assert.ok(backend.includes("ADMIN_REQUIRED")&&backend.includes("DELETE FROM users WHERE id <> ?"),'supervision reset must preserve the active administrator');
assert.ok(backend.includes("DELETE FROM dafat")&&backend.includes("system_flags")&&backend.includes("RESET_KEY"),'one-time Dafat/account reset is required');
assert.ok(backend.includes("academic_level")&&backend.includes("academic_stage")&&backend.includes("academic_field"),'supervision filters must use level/stage/field');
assert.ok(backend.includes("students/")||backend.includes("supervision\\/students"),'student moderation routes missing');
assert.ok(backend.includes("teachers\\/")&&backend.includes("dafat\\/"),'teacher and Dafaa moderation routes missing');
assert.ok(router.includes('dispatchAdminSupervision'),'generic API router must expose admin supervision');
assert.ok(routes.includes("currentActor.studentStage !== 'university'")&&!routes.includes('REPRESENTER_ACCOUNT_REQUIRED'),'higher-education students must be able to create a Dafaa');
assert.ok(!routes.includes('ensureRepresenterAccount(context.env.DB, owner.id'),'creating a Dafaa must not convert a student account into a representer account');
assert.ok(dafaUi.includes("actor?.studentStage==='university'"),'Dafaa create button must be visible to higher-education students');
assert.ok(auth.includes('prepareAcademicProfileInsert')&&!auth.includes("studentStage === 'school' ? await prepare"),'all student signups must persist academic identity');
assert.ok(profile.includes('CREATE TABLE IF NOT EXISTS student_academic_profiles')&&!profile.includes('ensureSchoolTeacherSchema'),'academic profile persistence must remain independent from Dafaa/school schema bootstrap');
assert.ok(ui.includes('admin-filter-form')&&ui.includes("['students','dafat','teachers']"),'admin supervision UI tabs/filters missing');
assert.ok(index.includes('admin-supervision.css')&&index.includes('admin-supervision.js'),'admin supervision assets must be loaded');
const roles=fs.readFileSync('role-panels.js','utf8');
assert.ok(ui.includes('DafatiiAdminSupervision')&&roles.includes("page==='admin'&&!window.DafatiiAdminSupervision"),'legacy admin loader must not race the supervision page');
console.log('admin supervision regression tests passed');
