const fs=require('node:fs');
const assert=require('node:assert/strict');
const ui=fs.readFileSync('calendar.js','utf8');
const css=fs.readFileSync('calendar.css','utf8');
const course=fs.readFileSync('course-context.js','utf8');
const index=fs.readFileSync('index.html','utf8');

assert.ok(ui.includes("const PLANNER_MODES = ['day','week','month','year']"), 'schedule must expose day/week/month/year time scales');
assert.ok(ui.includes('data-planner-loop="mode"') && ui.includes('data-planner-loop="period"'), 'schedule needs two independent horizontal looping selectors');
assert.ok(ui.includes("[-7,-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6,7]") && ui.includes('addDate(plannerDate,plannerMode'), 'period selector must generate a wide endless moving window around the selected date');
assert.ok(ui.includes("PLANNER_TABS = ['tasks','schedule','todos','goals','attendance']"), 'each selected period needs task, schedule, todo, goal and attendance content');
assert.ok(ui.includes("const LEGACY_PLANNER_KEY = 'dafatii:schedulePlanner:v1'") && ui.includes("const PLANNER_KEY = 'dafatii:schedulePlanner:v2'") && ui.includes('plannerPersonalKey') && ui.includes('window.DafatiiData.writeJSON(plannerPersonalKey(version),value)') && !course.includes("'dafatii:schedulePlanner:v2'"), 'planner must use a personal per-course synced record instead of shared Course content');
assert.ok(ui.includes('plannerItems()') && ui.includes('savePlannerItems') && ui.includes("date:String(form.get('date')"), 'planner entries must be canonical dated records rather than independent period buckets');
assert.ok(ui.includes('Array.from({length:24}') && ui.includes('Array.from({length:7}') && ui.includes('Array.from({length:30}') && ui.includes('Array.from({length:12}'), 'day/week/month/year views must render 24 hours, 7 days, 30 cells and 12 months');
assert.ok(ui.includes('function weekHours(days)') && ui.includes('planner-week-corner">Time') && ui.includes('planner-week-time') && ui.includes('planner-week-day'), 'week view must render a real timetable with day columns and time rows');
assert.ok(!ui.includes('data-planner-cell-add'), 'planner tables must not expose per-cell add buttons; adding is centralized in Manage Content');
assert.ok(ui.includes('data-planner-add-type') && ui.includes("plannerTypeMeta = Object.freeze"), 'planner must expose typed add proxies for task, to-do, goal, schedule and attendance');
assert.ok(ui.includes("let plannerTab = 'schedule'"), 'Schedule must be the default planner subpage');
assert.ok(ui.includes("const hasDateRails=['tasks','schedule','todos','goals'].includes(plannerTab)") && ui.includes('planner-date-controls') && ui.includes('data-planner-loop="mode"') && ui.includes('data-planner-loop="period"'), 'Tasks, Schedule, To-do and Goals must all keep the same two date picker rails');
assert.ok(ui.includes('function plannerPeriodBounds()') && ui.includes('function plannerPeriodItems(type)'), 'non-table planner subpages must filter their data by the shared selected day/week/month/year period');
assert.ok(!ui.includes('planner-task-dashboard') && !ui.includes('planner-todo-group'), 'retired task dashboard and old grouped to-do subpage markup must be removed from the renderer');
assert.ok(ui.includes("if(plannerTab==='schedule')return scheduleTableContent()") && ui.includes("if(plannerTab==='tasks')return tasksSubpage()") && ui.includes("if(plannerTab==='todos')return todosSubpage()") && ui.includes("if(plannerTab==='goals')return goalsSubpage()"), 'only Schedule may render the timetable; tasks, to-do and goals must use dedicated subpage renderers');
assert.ok(ui.includes('function tasksSubpage()') && ui.includes('function todosSubpage()') && ui.includes('function goalsSubpage()'), 'task, to-do and goal sections must have purpose-built premium subpages');
assert.ok(ui.includes('planner-v6-task-board') && ui.includes('data-planner-task-state') && ui.includes('estimatedMinutes') && ui.includes("taskLane('Ready'") && ui.includes("taskLane('In focus'"), 'rebuilt Tasks must use a period-scoped execution board with estimates and explicit workflow lanes');
assert.ok(ui.includes('planner-v6-todo-notebook') && ui.includes('data-planner-todo-important') && ui.includes('data-planner-todo-tomorrow') && ui.includes('data-planner-clear-completed') && ui.includes('listLabel'), 'rebuilt To-do must be a list notebook with importance, move-to-tomorrow and completed cleanup actions');
assert.ok(ui.includes('planner-v6-goal-grid') && ui.includes('goalTarget') && ui.includes('goalCurrent') && ui.includes('goalUnit') && ui.includes('goalStep') && ui.includes('data-planner-goal-step') && ui.includes('data-planner-goal-back'), 'rebuilt Goals must use measurable current/target/unit tracking with configurable forward and backward progress logging');
assert.ok(ui.includes('function scheduleDraftMarkup') && ui.includes('planner-add-schedule-row') && ui.includes('Up to 8 items in one save') && ui.includes('items.push(...payloads)'), 'Schedule Add must support creating multiple schedule items in one bottom sheet submission');
assert.ok(ui.includes('function scheduleItemOnDate(item,date)') && ui.includes("recurrence==='daily'") && ui.includes("recurrence==='weekly'") && ui.includes("recurrence==='monthly'"), 'schedule records must support one-time, daily, weekly and monthly recurrence');
assert.ok(ui.includes('data-schedule-field="repeat"') && ui.includes('data-schedule-field="recurrence"') && ui.includes('data-schedule-field="repeatUntil"') && ui.includes('data-schedule-field="endTime"'), 'schedule add/edit bottom sheet must include repeat, cadence, optional end date and end time');
assert.ok(ui.includes('schedule-block') && ui.includes('scheduleRepeatLabel(item)'), 'schedule items must render as premium full-cell timetable blocks');
assert.ok(ui.includes('data-planner-edit-recurring') && ui.includes("openTimetableEntrySheet('schedule',SCHEDULE_KEY,item)"), 'legacy/projected weekly schedule blocks must also open their edit form from unified edit mode');

assert.ok(ui.includes("name=\"estimatedMinutes\"") && ui.includes("name=\"listLabel\"") && ui.includes("name=\"todoImportant\"") && ui.includes("name=\"goalTarget\"") && ui.includes("name=\"goalCurrent\"") && ui.includes("name=\"goalUnit\"") && ui.includes("name=\"goalStep\""), 'task, to-do and goal forms must expose the rebuilt subpages distinct functional fields');
assert.ok(ui.includes("/^\\d{4}-\\d{2}-\\d{2}$/.test(payload.date)"), 'planner add/edit forms must accept valid ISO dates');
assert.ok(css.includes('.planner-week-grid') && css.includes('.planner-week-time') && css.includes('.planner-item-goals') && css.includes('.planner-goal-progress'), 'week timetable and premium planner item states must be styled');
assert.ok(css.includes('.schedule-block') && css.includes('.planner-task-card') && css.includes('.planner-todo-row') && css.includes('.planner-goal-card') && css.includes('.planner-repeat-panel'), 'schedule blocks, unique subpages and recurrence bottom sheet must have dedicated premium styling');
assert.ok(css.includes('.planner-v6-task-board') && css.includes('.planner-v6-todo-notebook') && css.includes('.planner-v6-goal-grid') && css.includes('.planner-date-controls') && css.includes('.planner-schedule-draft'), 'rebuilt productivity subpages, shared date rails and multi-schedule builder must have dedicated premium presentation');
assert.ok(css.includes('width:min(520px,calc(100vw - 24px))!important') && css.includes('width:calc(100vw - 12px)!important') && css.includes('overflow-x:hidden!important'), 'planner bottom sheets must stay compact and within the viewport without width overflow');
assert.ok(ui.includes("plannerMode='day'") && ui.includes("plannerMode='month'"), 'aggregate tables must drill into the same dated data across time scales');
assert.ok(ui.includes('centeredPlannerItem') && ui.includes("track.addEventListener('scroll'") && ui.includes("track.addEventListener('scrollend'"), 'scroll position must select the item nearest the center of each rail');
assert.ok(ui.includes("item.style.opacity") && ui.includes("distance/fadeDistance"), 'selection opacity must fall continuously as items move away from the rail center');
assert.ok(!ui.includes('planner-loop-arrow') && !ui.includes('data-planner-mode-step') && !ui.includes('data-planner-period-step'), 'schedule selectors must not render arrow buttons');
assert.ok(ui.includes('function recurringForDate(date)') && ui.includes('const entries=read(SCHEDULE_KEY,[])') && ui.includes("notes:'Recurring weekly timetable'"), 'existing weekly schedule data must project into matching dated schedule cells');
assert.ok(css.includes('.planner-loop-shell{position:relative') && css.includes('border:0') && css.includes('background:transparent') && css.includes('scroll-snap-type:x mandatory'), 'selector rails must be frameless horizontal scroll-snap controls');
assert.ok(css.includes('.planner-content-tabs') && css.includes('.planner-day-table') && css.includes('.planner-week-grid') && css.includes('.planner-month-table') && css.includes('.planner-year-table'), 'all four interconnected schedule tables must be styled');
assert.ok(index.includes('calendar.js?v=20260919-11') && index.includes('calendar.css?v=20260919-7'), 'schedule redesign assets must be cache-busted');
console.log('calendar schedule redesign tests passed');

assert.ok(ui.includes('legacyPlannerSnapshot') && ui.includes('__dafatii:course-cache:'), 'planner migration must recover any locally cached pre-fix planner data without resubmitting it as Course content');
