const fs=require('node:fs');
const assert=require('node:assert/strict');
const ui=fs.readFileSync('student-social.js','utf8');
const css=fs.readFileSync('student-social.css','utf8');
const advanced=fs.readFileSync('advanced-chat.js','utf8');
const advancedCss=fs.readFileSync('advanced-chat.css','utf8');
const shell=fs.readFileSync('quiet-shell.js','utf8');
const quiet=fs.readFileSync('quiet-design.css','utf8');
const index=fs.readFileSync('index.html','utf8');

assert.ok(ui.includes("const CHAT_SUBNAV = ['Private chats','Groups','Blogs & announcements','Anonymous'];"), 'chat app must expose private/groups/blogs/anonymous destinations');
assert.ok(ui.includes('function chatAppShell(') && ui.includes('class="chat-app-topbar"') && ui.includes('class="chat-app-subnav"') && ui.includes('class="chat-app-bottom"'), 'chat app must own its top bar, page sub-navigation, and special bottom dock');
assert.ok(ui.includes('id="chat-app-profile"') && ui.includes('id="chat-app-profile-popover"') && ui.includes('aria-controls="chat-app-profile-popover"'), 'Chat avatar must toggle a Chat-specific profile surface');
assert.ok(!ui.includes('id="chat-app-search-top"') && !ui.includes('class="chat-app-brand"'), 'Chat top bar must remain minimal: profile avatar plus menu only');
assert.ok(ui.includes('class="chat-app-drawer"') && ui.includes('id="chat-app-menu"'), 'chat app must include its own sidebar/drawer access');
assert.ok(ui.includes('href="#dashboard"') && ui.includes('Return to dashboard'), 'chat app must provide explicit return paths to the main website');
assert.ok(ui.includes('function chatFeedView()') && ui.includes('Blogs & announcements'), 'chat app must have a distinct blogs and announcements page');
assert.ok(ui.includes('chatThreadRoute') && ui.includes('parts[2]') && ui.includes('data-chat-selected'), 'conversation list and conversation thread must be separate routes');
assert.ok(ui.includes("setHash(chatThreadRoute(kind,btn.dataset.chatOpen))"), 'opening a chat card must navigate into its thread page');
assert.ok(ui.includes("setHash(chatThreadRoute(kind,id))"), 'new conversations must open their own thread route');
assert.ok(shell.includes("shell.classList.toggle('chat-app-host',current.split('/')[0]==='chat')"), 'shared shell must activate dedicated chat host mode for list and nested thread routes');
assert.ok(quiet.includes('.quiet-workspace.chat-app-host>.quiet-toolbar') && quiet.includes('.quiet-workspace.chat-app-host>.bottom-nav') && quiet.includes('display:none!important'), 'main workspace navigation must not overlap the chat app');
for(const marker of ['.chat-app-topbar','.chat-app-profile-popover','.chat-app-subnav','.chat-app-drawer','.chat-app-bottom','.chat-directory','.chat-feed-grid','.chat-thread-page']) assert.ok(css.includes(marker), marker+' style missing');
assert.ok(index.includes('student-social.js?v=20260919-1') && index.includes('student-social.css?v=20260919-3'), 'chat app shell assets must be cache-busted');
assert.ok(index.includes('advanced-chat.js?v=20260919-2') && index.includes('advanced-chat.css?v=20260919-3'), 'advanced chat integration assets must be cache-busted');
assert.ok(ui.includes('window.DafatiiChatShell = Object.freeze'), 'student social must export the canonical Chat app shell for later chat enhancements');
assert.ok(advanced.includes("if(section.toLowerCase()==='blogs & announcements')return previousWorkspaceContent"), 'advanced chat must defer Blogs & announcements to the canonical Chat feed');
assert.ok(advanced.includes('window.DafatiiChatShell?.render?.(section,content,{thread:Boolean(selected),subpage:ui.filter})'), 'advanced chat must render inside the canonical Chat app shell and pass the active contextual subpage');
assert.ok(advanced.includes("const requestedId=parts[2]?decodeURIComponent(parts[2]):''"), 'advanced chat list and thread must use separate nested routes');
assert.ok(advanced.includes('class="chatpro-shell list-only"') && advanced.includes('class="chatpro-shell thread-only"'), 'advanced chat must render route-specific list and thread shells');
assert.ok(advanced.includes('setHash(chatThreadRoute(kind,row.dataset.openChat))'), 'advanced conversation cards must navigate to nested thread routes');
assert.ok(advanced.includes('aria-label="Back to chats"') && !advanced.includes('class="chatpro-head-actions"'), 'thread header must contain only the return control and conversation profile');
assert.ok(css.includes('.chat-app-page.thread-open>.chat-app-topbar') && css.includes('.chat-app-page.thread-open>.chat-app-bottom') && css.includes('display:none!important'), 'thread routes must hide the Chat app chrome');
assert.ok(advancedCss.includes('.chat-app-page.thread-open .chat-app-stage .chatpro-shell.thread-only') && advancedCss.includes('height:100dvh') && advancedCss.includes('.chat-app-page.thread-open .chatpro-composer-zone'), 'thread routes must fill the viewport with header/messages/composer layout');
assert.ok(css.includes('position:fixed;inset:0;z-index:90') && advancedCss.includes('position:relative;inset:auto;z-index:12'), 'open-thread viewport must be fixed while the composer remains the final grid row');
assert.ok(advancedCss.includes('backdrop-filter:blur(26px) saturate(150%)') && advancedCss.includes('box-shadow:0 12px 34px'), 'fixed composer must use the premium glass/pill treatment');
assert.ok(advanced.includes('data-chat-composer') && advanced.includes("zone?.addEventListener('pointerdown',keepComposerInteractionLocal)") && advanced.includes("zone?.addEventListener('focusin',keepComposerInteractionLocal)"), 'composer interactions must not bubble into outer workspace navigation');
assert.ok(advanced.includes('type="button" id="chatpro-attach"') && advanced.includes('type="button" id="chatpro-send"') && advanced.includes('enterkeyhint="send"'), 'composer controls must have explicit non-submit semantics and mobile send intent');
assert.ok(advancedCss.includes('.chat-app-stage .chatpro-shell.list-only') && advancedCss.includes('.chat-app-stage .chatpro-shell.thread-only'), 'advanced chat must be sized inside the dedicated Chat app chrome');
console.log('chat app redesign tests passed');

assert.ok(ui.includes("const CHAT_SECTION_SUBPAGES = {") && ui.includes("'Private chats':[['all','All'],['unread','Unread'],['starred','Starred'],['archived','Archived']]"), 'Private chats must expose its own contextual subpages under the top bar');
assert.ok(ui.includes("'Groups':[['all','All groups'],['unread','Unread'],['starred','Starred'],['archived','Archived']]"), 'Groups must expose its own contextual subpages');
assert.ok(ui.includes("'Blogs & announcements':[['latest','Latest'],['announcement','Announcements'],['blog','Blogs'],['study','Study tips']]"), 'Blogs must expose feed-specific subpages');
assert.ok(ui.includes("'Anonymous':[['all','All'],['unread','Unread'],['starred','Starred'],['archived','Archived']]"), 'Anonymous must expose its own contextual subpages');
assert.ok(ui.includes('data-chat-subpage=') && ui.includes('chatSubpages(section)'), 'the row below the top bar must render contextual subpage controls, not duplicate main Chat navigation');
assert.ok(ui.includes("chatAppNavItem(section,'Private chats','chat')") && ui.includes("chatAppNavItem(section,'Groups','groups')") && ui.includes("chatAppNavItem(section,'Blogs & announcements','news')") && ui.includes("chatAppNavItem(section,'Anonymous','anonymous')"), 'the bottom dock must remain the main Chat navigation');
assert.ok(ui.includes("const CHAT_ICON_PATHS = {") && ui.includes("function chatIcon(name"), 'Chat must use one consistent SVG icon system');
assert.ok(advanced.includes("const icon=(name,extra='')=>window.DafatiiChatShell?.icon?.(name,extra)||'';"), 'advanced chat must consume the canonical SVG icon family');
assert.ok(advanced.includes("subpage:ui.filter"), 'advanced list filters must drive the contextual top subnav');
assert.ok(advanced.includes("document.querySelectorAll('[data-chat-subpage]')"), 'advanced list subpages must be interactive');
assert.ok(!advanced.includes("${statusStrip(kind,state)}") && !advanced.includes("${filterBar()}"), 'premium list pages must not duplicate contextual subnavigation with stories or a second filter bar');
assert.ok(advancedCss.includes('Premium messenger surfaces v4') && advancedCss.includes('.chatpro-conversation+.chatpro-conversation:before'), 'conversation list must use the premium simplified row design');
assert.ok(css.includes('Premium Chat app v4') && css.includes('.chat-app-topbar') && css.includes('.chat-app-bottom'), 'all Chat chrome must use the premium v4 visual system');
