const fs=require('node:fs');
const assert=require('node:assert/strict');
const ui=fs.readFileSync('student-social.js','utf8');
const css=fs.readFileSync('student-social.css','utf8');
const advanced=fs.readFileSync('advanced-chat.js','utf8');
const advancedCss=fs.readFileSync('advanced-chat.css','utf8');
const shell=fs.readFileSync('quiet-shell.js','utf8');
const quiet=fs.readFileSync('quiet-design.css','utf8');
const index=fs.readFileSync('index.html','utf8');

assert.ok(ui.includes("const CHAT_SUBNAV = ['Private chats','Groups','Blogs & announcements','Anonymous'];"), 'chat app must expose private/groups/blogs/anonymous destinations');
assert.ok(ui.includes('function chatAppShell(') && ui.includes('class="chat-app-topbar"') && ui.includes('class="chat-app-subnav"') && ui.includes('class="chat-app-bottom"'), 'chat app must own its top bar, page sub-navigation, and special bottom dock');
assert.ok(ui.includes('class="chat-app-drawer"') && ui.includes('id="chat-app-menu"'), 'chat app must include its own sidebar/drawer access');
assert.ok(ui.includes('href="#dashboard"') && ui.includes('Return to dashboard'), 'chat app must provide explicit return paths to the main website');
assert.ok(ui.includes('function chatFeedView()') && ui.includes('Blogs & announcements'), 'chat app must have a distinct blogs and announcements page');
assert.ok(ui.includes('chatThreadRoute') && ui.includes('parts[2]') && ui.includes('data-chat-selected'), 'conversation list and conversation thread must be separate routes');
assert.ok(ui.includes("setHash(chatThreadRoute(kind,btn.dataset.chatOpen))"), 'opening a chat card must navigate into its thread page');
assert.ok(ui.includes("setHash(chatThreadRoute(kind,id))"), 'new conversations must open their own thread route');
assert.ok(shell.includes("shell.classList.toggle('chat-app-host',current==='chat')"), 'shared shell must activate dedicated chat host mode');
assert.ok(quiet.includes('.quiet-workspace.chat-app-host>.quiet-toolbar') && quiet.includes('.quiet-workspace.chat-app-host>.bottom-nav') && quiet.includes('display:none!important'), 'main workspace navigation must not overlap the chat app');
for(const marker of ['.chat-app-topbar','.chat-app-subnav','.chat-app-drawer','.chat-app-bottom','.chat-directory','.chat-feed-grid','.chat-thread-page']) assert.ok(css.includes(marker), marker+' style missing');
assert.ok(index.includes('student-social.js?v=20260918-3') && index.includes('student-social.css?v=20260918-2'), 'chat app shell assets must be cache-busted');
assert.ok(index.includes('advanced-chat.js?v=20260918-2') && index.includes('advanced-chat.css?v=20260918-2'), 'advanced chat integration assets must be cache-busted');
assert.ok(ui.includes('window.DafatiiChatShell = Object.freeze'), 'student social must export the canonical Chat app shell for later chat enhancements');
assert.ok(advanced.includes("if(section.toLowerCase()==='blogs & announcements')return previousWorkspaceContent"), 'advanced chat must defer Blogs & announcements to the canonical Chat feed');
assert.ok(advanced.includes('window.DafatiiChatShell?.render?.(section,content,{thread:Boolean(selected)})'), 'advanced chat must render inside the canonical Chat app shell rather than replacing it');
assert.ok(advanced.includes("const requestedId=parts[2]?decodeURIComponent(parts[2]):''"), 'advanced chat list and thread must use separate nested routes');
assert.ok(advanced.includes('class="chatpro-shell list-only"') && advanced.includes('class="chatpro-shell thread-only"'), 'advanced chat must render route-specific list and thread shells');
assert.ok(advanced.includes('setHash(chatThreadRoute(kind,row.dataset.openChat))'), 'advanced conversation cards must navigate to nested thread routes');
assert.ok(advancedCss.includes('.chat-app-stage .chatpro-shell.list-only') && advancedCss.includes('.chat-app-stage .chatpro-shell.thread-only'), 'advanced chat must be sized inside the dedicated Chat app chrome');
console.log('chat app redesign tests passed');
