const fs=require('node:fs');
const assert=require('node:assert/strict');
const js=fs.readFileSync('course-modes.js','utf8');
const css=fs.readFileSync('course-modes.css','utf8');
const index=fs.readFileSync('index.html','utf8');

for(const route of ['language-home','language-letters','language-voice','language-grammar','language-video','language-examine']) assert.ok(js.includes("'"+route+"'"),'missing language route '+route);
for(const language of ['English','Arabic','Spanish','French','German','Turkish','Persian','Kurdish','Italian','Portuguese','Russian','Chinese','Japanese','Korean','Hindi','Urdu']) assert.ok(js.includes("['"+language+"'"),'missing language '+language);

assert.match(js,/LANGUAGE_CONTENT_KEY = 'dafatii:language-content:v2'/,'language item storage key missing');
assert.match(js,/LANGUAGE_ITEM_EXAMPLES/,'item examples registry missing');
assert.match(js,/data-language-add-examples/,'page example action missing');
assert.match(js,/data-language-use-example/,'item example action missing');
assert.match(js,/LANGUAGE_PAGE_ITEM_TYPES/,'page-specific item catalog missing');
for(const type of ['letter','word-translation','image-word','sentence-pair','spelling-write','handwriting','pronunciation','text-to-voice','image-to-voice','voice-to-text','voice-to-image','voice-pair','grammar-topic','grammar-rule','grammar-example','grammar-training','youtube-video','story','reading','single-choice','multiple-choice','true-false','fill-blank','ordering','short-answer']) assert.ok(js.includes("'"+type+"'"),'missing language item type '+type);
for(const type of ['vocab-course-to-native','vocab-sentence-to-native','vocab-native-to-course','vocab-image-to-course','vocab-course-to-image','write-native-to-course','write-image-to-course','write-native-question-to-course-answer','write-course-question-to-course-answer','write-course-to-native','listen-course-to-native','listen-course-sentence-to-native','listen-native-to-course','listen-image-to-course','listen-course-to-image','speak-native-to-course','speak-image-to-course','speak-native-question-to-course-answer','speak-course-question-to-course-answer','speak-course-to-native']) assert.ok(js.includes("'"+type+"'"),'missing directional language item type '+type);
assert.match(js,/toggleLanguageMicrophone/,'speaking microphone control missing');
assert.match(js,/navigator\.mediaDevices\.getUserMedia/,'speaking items must request microphone access on demand');
assert.match(js,/data-language-mic/,'speaking microphone button missing');
assert.match(js,/data-language-speak/,'listening control missing');
assert.match(js,/openLanguageItemEditor/,'item add/edit UI missing');
assert.match(js,/data-language-edit/,'item edit control missing');
assert.match(js,/data-language-delete/,'item deletion control missing');
assert.match(js,/data-language-share/,'shared item action missing');
assert.match(js,/speechSynthesis/,'pronunciation interaction missing');
assert.match(js,/youtube-nocookie.com/,'safe YouTube item renderer missing');
assert.match(js,/function languageItemsPage/,'language page renderer missing');
assert.match(js,/.language-items-page/,'premium language item layout missing');
assert.match(css,/.language-item-card/,'language item card design missing');
assert.match(css,/.theme-vocabulary/,'page theme tokens missing');
assert.match(css,/.language-item-editor/,'item editor styling missing');
assert.ok(index.includes('course-modes.css?v=20260922-27'),'CSS cache version missing');
assert.ok(index.includes('course-modes.js?v=20260922-26'),'JS cache version missing');
assert.match(js,/personal-focus-room/,'personal course behavior changed');
console.log('language content item type tests passed');
