import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { webcrypto } from 'node:crypto';
globalThis.crypto ||= webcrypto;
const { assertContentPermissions, fullPermissions, noPermissions, permissionInput, requiredContentPermissions, validateCourseInput, validateMemberPatch, validateProfileInput } = await import('../functions/_lib/courses.mjs');

assert.deepEqual(validateProfileInput({accountType:'representer',studentStage:'school'}),{accountType:'representer',studentStage:'school'});
assert.throws(()=>validateProfileInput({accountType:'admin'}),error=>error.code==='INVALID_INPUT');
assert.equal(validateCourseInput({name:'Biology',pricing:'paid',priceMinor:1250,visibility:'public',joinPolicy:'approval',learningField:'Biology',difficultyLevel:'intermediate'}).priceMinor,1250);
assert.equal(validateCourseInput({name:'Biology',learningField:'Life Sciences',difficultyLevel:'advanced'}).difficultyLevel,'advanced');
assert.throws(()=>validateCourseInput({name:'Biology',difficultyLevel:'impossible'}),error=>error.code==='INVALID_DIFFICULTY_LEVEL');
assert.throws(()=>validateCourseInput({name:'X'}),error=>error.code==='INVALID_COURSE_NAME');
assert.deepEqual([...requiredContentPermissions(undefined,[{id:'a'}])],['can_add_content']);
assert.deepEqual([...requiredContentPermissions([{id:'a',name:'A'}],[{id:'a',name:'B'},{id:'b'}])].sort(),['can_add_content','can_edit_content']);
assert.deepEqual([...requiredContentPermissions([{id:'a'}],[])],['can_remove_content']);
assert.deepEqual([...requiredContentPermissions([{id:'a'}],undefined,true)],['can_remove_content']);
const row={membership_status:'active',membership_role:'representer',...noPermissions(),can_add_content:1};
assert.doesNotThrow(()=>assertContentPermissions(row,{isAdmin:false},new Set(['can_add_content'])));
assert.throws(()=>assertContentPermissions(row,{isAdmin:false},new Set(['can_remove_content'])),error=>error.status===403);
assert.equal(Object.values(fullPermissions()).every(Boolean),true);
assert.equal(permissionInput({can_manage_students:true}).can_manage_students,1);
assert.equal(validateMemberPatch({role:'representer',status:'active'}).role,'representer');

const migration=readFileSync(new URL('../migrations/0002_course_rbac.sql',import.meta.url),'utf8');
const discoveryMigration=readFileSync(new URL('../migrations/0007_course_discovery_onboarding.sql',import.meta.url),'utf8');
assert.match(migration,/CREATE TABLE course_memberships/);
assert.match(migration,/can_manage_representers/);
assert.match(migration,/ALTER TABLE files ADD COLUMN course_id/);
for (const column of ['academic_level','academic_stage','academic_field','learning_field','difficulty_level']) assert.match(discoveryMigration,new RegExp(column));
const routes=readFileSync(new URL('../functions/_lib/course-routes.mjs',import.meta.url),'utf8');
assert.match(routes,/requirePermission/);
assert.match(routes,/assertContentPermissions/);
assert.match(routes,/SELF_LOCKOUT_REJECTED/);
assert.match(routes,/PUBLIC_COURSE_ADMIN_REQUIRED/);
assert.match(routes,/studentAcademicIdentity/);
assert.match(routes,/ensureCourseDiscoverySchema/);
const gate=readFileSync(new URL('../functions/_lib/course-gate.mjs',import.meta.url),'utf8');
assert.match(gate,/readJson\(context\.request\.clone\(\), 65536\)/, 'course create/update gate must preserve the bounded request parser');
assert.doesNotMatch(gate,/context\.request\.clone\(\)\.json\(\)/, 'course gate must not parse an unbounded cloned request body');
const optionalRoute=readFileSync(new URL('../functions/api/v1/courses/[[path]].js',import.meta.url),'utf8');
assert.match(optionalRoute,/child \? `courses\/\$\{child\}` : 'courses'/, 'bare /api/v1/courses must dispatch as courses, not courses/');
assert.doesNotMatch(optionalRoute,/`courses\/\$\{joinedPath\(context\.params\?\.path\)\}`/, 'optional catch-all must not append a trailing slash for an empty path');
console.log('course RBAC tests passed');
