const assert = require('node:assert/strict');
const fs = require('node:fs');

const script = fs.readFileSync('file-reader-interactions.js', 'utf8');
const css = fs.readFileSync('file-reader-interactions.css', 'utf8');
const workspace = fs.readFileSync('viewer-workspace.js', 'utf8');
const design = fs.readFileSync('lecture-reader-design.css', 'utf8');
const workspaceCss = fs.readFileSync('viewer-workspace.css', 'utf8');
const index = fs.readFileSync('index.html', 'utf8');

assert.match(script, /reader-loading/, 'file readers must enter a dedicated loading state');
assert.match(script, /reader-ready/, 'file readers must expose a ready state before content is revealed');
assert.match(script, /data-viewer-loading-screen/, 'file readers must mount a full loading screen');
assert.match(script, /originalPdf\.open[\s\S]*await originalOpen[\s\S]*reveal\(root\)/, 'PDF content must remain gated until its initial render completes');
assert.match(script, /status\.hidden[\s\S]*reveal\(root\)/, 'Office content must remain gated until the renderer reports ready');
assert.match(script, /event\.touches\.length !== 2/, 'pinch zoom must require exactly two touch points');
assert.match(script, /event\.preventDefault\(\)/, 'custom pinch zoom must suppress browser page zoom while active');
assert.match(script, /controls\.zoomIn|controls\.zoomOut/, 'pinch gestures must use the viewer zoom API');
assert.match(script, /Math\.hypot/, 'pinch zoom must calculate two-finger distance');
assert.match(script, /addEventListener\('dblclick',reset/, 'desktop double-click must reset file zoom');
assert.match(script, /addEventListener\('touchend',event=>/, 'mobile double-tap detection must be installed');
assert.match(script, /controls\.resetZoom\(\)/, 'double click/tap must call the renderer baseline reset for 0% magnification');
assert.match(script, /readerMagnification = '0'/, 'double click/tap must explicitly mark the viewer as 0% magnification');
assert.match(script, /0% magnification/, 'the reader hint must describe double click/tap as returning to 0% magnification');
assert.match(workspace, /aria-label="\$\{esc\(t\('switchLecture'\)\)\}"/, 'icon-only reader controls must keep accessible labels');
assert.doesNotMatch(workspace, /<small>\$\{esc\(t\('switchLecture'\)\)\}<\/small>/, 'reader dock must not show text below the switch icon');
assert.doesNotMatch(design, /\.viewer-reader-dock small/, 'reader dock CSS must not reserve space for text labels');
assert.match(design, /grid-template-columns:repeat\(4,52px\)/, 'desktop reader controls must use compact circular icon slots');
assert.match(script, /reader-chrome-hidden/, 'reader chrome must auto-hide while document content is scrolling');
assert.match(script, /addEventListener\('scroll',onScroll/, 'reader auto-hide must be driven by the document stage scroll event');
assert.match(workspace, /data-viewer-dock="switch"/, 'file reader must expose the switch lecture action');
assert.match(workspace, /data-viewer-dock="navigate"/, 'file reader must expose lecture navigation');
assert.match(workspace, /data-viewer-dock="status"/, 'file reader must expose lecture status');
assert.match(workspace, /data-viewer-dock="examine"/, 'file reader must expose examine tools');
assert.match(workspace, /data-reader-settings/, 'file reader must expose the reference-style reader settings sheet');
assert.match(workspace, /data-reader-axis/, 'reader settings must support page direction where the renderer exposes it');
assert.match(design, /\.file-workspace \.reader-settings-button/, 'the reference reader must have a mirrored top settings control');
assert.match(design, /\.file-workspace \.viewer-reader-dock/, 'the reference reader must use the four-action floating dock');
assert.match(design, /\.viewer-status-list/, 'lecture status must use a dedicated sheet layout');
assert.match(design, /\.viewer-examine-list/, 'examine tools must use a dedicated sheet layout');
assert.match(workspace, /video-reader-topbar/, 'video viewer must use the reference-style minimal top bar');
assert.match(workspace, /video-reader-examine/, 'video viewer must expose Examine from the top bar');
assert.match(workspace, /if \(event\.defaultPrevented\) \{\s*onClose\?\.\(\);\s*return;/, 'accepted Flashcards, MCQ and Question & Answer actions must close either viewer before routing');
assert.match(workspace, /video-note-composer/, 'video viewer must include the inline note composer');
assert.match(workspace, /data-video-source-button/, 'video viewer must support switching note sources');
assert.match(workspace, /data-video-visibility="personal"/, 'video note composer must expose personal visibility');
assert.match(workspace, /dafatii:viewer-note-publish/, 'public video notes must delegate to an explicit integration instead of pretending to publish');
assert.match(workspaceCss, /\.video-reader-topbar/, 'video viewer CSS must define the minimal top bar');
assert.match(workspaceCss, /\.video-note-visibility/, 'video viewer CSS must define the visibility control');
assert.match(workspaceCss, /\.video-source-list/, 'video viewer CSS must define the notes-source sheet');
assert.doesNotMatch(workspace, /class="video-reader-scroll"/, 'video, title, and notes must not share one scrolling container');
assert.match(workspace, /data-video-notes-scroll/, 'video viewer must expose a dedicated notes scroller');
assert.match(workspaceCss, /grid-template-rows:72px var\(--video-player-height\) max-content minmax\(0,1fr\)/, 'desktop video viewer must use non-stretching fixed chrome and player tracks');
assert.match(workspaceCss, /\.video-notes-scroll\{[^}]*overflow-y:auto/, 'only the notes pane should scroll when content exceeds available height');
assert.match(workspaceCss, /--video-player-height:min\(50dvh,56\.25vw,520px\)/, 'video player height must adapt to the desktop viewport');
assert.match(workspaceCss, /grid-template-rows:calc\(60px \+ env\(safe-area-inset-top\)\) var\(--video-player-height\) max-content minmax\(0,1fr\)/, 'mobile viewer must reserve a compact safe-area top bar and fixed player track');
assert.match(workspaceCss, /\.video-reader-topbar\{[^}]*height:72px[^}]*min-height:0/, 'desktop top bar must not stretch');
assert.match(workspaceCss, /\.video-workspace-stage\{[^}]*height:100%[^}]*min-height:0/, 'player must fill its fixed grid track instead of sizing the shell');
assert.doesNotMatch(workspaceCss, /\.video-workspace \.immersive-viewer-shell\{grid-template-rows:minmax\(0,52%\) minmax\(0,48%\)\}/, 'legacy two-row mobile layout must not override the four-row video viewer and create a blank gap');
assert.match(css, /\.viewer-loading-screen\{/, 'the loading screen must cover the reader');
assert.match(css, /reader-loading[\s\S]*visibility:hidden/, 'document stages must remain hidden while loading');
assert.match(css, /touch-action:pan-x pan-y/, 'single-finger document scrolling must remain enabled while custom pinch zoom is active');
assert.match(index, /file-reader-interactions\.css\?v=20260917-1/, 'the loading and pinch styles must be loaded');
assert.match(index, /file-reader-interactions\.js\?v=20260919-3/, 'the loading, pinch, and chrome controller must be loaded');
assert.match(index, /viewer-workspace\.js\?v=20260919-5/, 'the redesigned reader and video controls must be loaded');
assert.match(index, /viewer-workspace\.css\?v=20260919-5/, 'the redesigned video viewer presentation must be loaded');
assert.match(index, /lecture-reader-design\.css\?v=20260919-2/, 'the redesigned file-reader presentation must be loaded');
assert.match(index, /pdf-viewer\.js\?v=20260919-1/, 'the PDF reader baseline reset must be loaded');
assert.match(index, /office-viewer\.js\?v=20260919-1/, 'the Office reader with zoom reset must be loaded');

console.log('file reader loading and pinch checks passed');
