const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const featureFiles = ['app.js', 'academic.js', 'calendar.js', 'student-suite.js', 'advanced-chat.js', 'study-room-workspace.js', 'dafaa-context.js', 'dafaa-ui.js'];
for (const file of featureFiles) {
  const source = fs.readFileSync(file, 'utf8');
  assert.doesNotMatch(source, /fetch\s*\(\s*['"`]\/api\//, `${file} must not call backend endpoints directly`);
  assert.doesNotMatch(source, /GCS_|storage\.googleapis\.com|cloudflare/i, `${file} must stay provider-independent`);
}
for (const file of fs.readdirSync('.').filter(name => name.endsWith('.js'))) {
  const source = fs.readFileSync(file, 'utf8');
  assert.doesNotMatch(source, /-----BEGIN PRIVATE KEY-----|private_key_id|GCS_PRIVATE_KEY\s*=/, `${file} contains a secret-like value`);
}
const adapter = fs.readFileSync('backend-adapter.js', 'utf8');
assert.match(adapter, /baseRevision/);
assert.match(adapter, /mutationId/);
assert.match(adapter, /status === 409/);
const router = fs.readFileSync(path.join('functions', 'api', 'v1', '[[path]].js'), 'utf8');
assert.match(router, /WHERE id = \? AND user_id = \?/);
assert.match(router, /INSERT OR IGNORE INTO records/);
assert.match(router, /status = 'available'/);
assert.match(fs.readFileSync('index.html', 'utf8'), /rel="icon" type="image\/svg\+xml"/);
assert.match(fs.readFileSync('index.html', 'utf8'), /dafaa-context\.js/);
assert.match(fs.readFileSync('index.html', 'utf8'), /dafaa-ui\.js/);
const index = fs.readFileSync('index.html', 'utf8');
assert.match(index, /quiet-design\.css\?v=24/, 'the consolidated presentation layer must be loaded');
assert.match(index, /device-layout\.js\?v=2/, 'device-aware navigation classification must load before rendering');
assert.match(index, /icon-system\.js\?v=3/, 'the unified icon system must load before the interface');
assert.match(index, /card-swipe\.js\?v=1/, 'the safe card gesture controller must be loaded');
assert.match(index, /quiet-shell\.js\?v=11/, 'the consolidated responsive shell must be loaded');
assert.match(index, /translation-client\.js\?v=1/, 'the authenticated interface translator must be loaded');
assert.match(index, /app\.js\?v=20260915-3/, 'the cleaned subject interface must be loaded');
assert.match(index, /calendar\.js\?v=20260915-4/, 'the cleaned calendar interface must be loaded');
assert.match(index, /calendar\.css\?v=20260915-4/, 'retired calendar toolbar styling must be removed from the active asset');
assert.match(index, /role-panels\.js\?v=20260915-2/, 'the redesigned dashboard management entry must be loaded');
assert.match(index, /role-panels\.css\?v=20260915-2/, 'the redesigned management entry styling must be loaded');
assert.doesNotMatch(index, /premium-theme\.css|premium-shell\.js|navigation-layout(?:-fix)?\.css/, 'retired presentation layers must not be loaded');
const quietShell = fs.readFileSync('quiet-shell.js', 'utf8');
const quietDesign = fs.readFileSync('quiet-design.css', 'utf8');
assert.doesNotMatch(quietDesign, /Unified interaction system v8/, 'late override layers must not be appended to the canonical stylesheet');
assert.match(quietDesign, /@media\(max-width:767px\).*\.landing-nav-tabs\{position:fixed;left:50%;right:auto;bottom:max\(10px,env\(safe-area-inset-bottom\)\);[^}]*width:min\(calc\(100% - 24px\),440px\);height:64px/s, 'mobile landing navigation must match the authenticated floating icon dock');
assert.match(quietDesign, /@media\(min-width:768px\) and \(max-width:1199px\).*\.landing-nav\{position:fixed;inset-block:0;inset-inline-start:0/s, 'tablet landing navigation must use a side rail');
assert.match(quietDesign, /\.landing-nav\{position:sticky;top:0/s, 'desktop landing navigation must remain above the page');
assert.match(quietDesign, /html\[data-device=mobile\] \.landing-nav-tabs\{position:fixed;left:50%;right:auto;bottom:max\(10px,env\(safe-area-inset-bottom\)\);[^}]*height:64px/s, 'phone user agents must force the shared bottom icon navigation');
assert.match(quietDesign, /html\[data-device=tablet\] \.landing-nav\{position:fixed;inset-block:0/s, 'tablet user agents must force the side landing navigation');
assert.match(quietDesign, /@media\(max-width:1100px\) and \(max-aspect-ratio:5\/8\).*\.landing-nav-tabs\{position:fixed;left:50%;right:auto;bottom:max\(10px,env\(safe-area-inset-bottom\)\);[^}]*height:64px/s, 'tall privacy-restricted phone containers need the shared bottom icon navigation');
assert.ok(
  quietDesign.lastIndexOf('@media(max-width:1100px) and (max-aspect-ratio:5/8)') > quietDesign.indexOf('.landing-nav{position:sticky;top:0'),
  'the phone-shaped viewport fallback must come after the desktop navigation rule'
);
assert.match(quietDesign, /html\[data-device=mobile\] \.landing-nav\{[^}]*backdrop-filter:none;[^}]*contain:none\}/, 'mobile landing header must not create a fixed-position containing block');
assert.match(quietShell, /data-quiet-menu/, 'the responsive sidebar needs an access button');
assert.match(quietShell, /currentRoute=route\(\),current=activePage\(\)/, 'return visibility must use the complete route while main navigation highlighting uses the section');
assert.match(quietShell, /showReturnButton=!primaryDestinations\.has\(normalizedRoute\(currentRoute\)\)/, 'the floating return control must be hidden only on exact primary navigation destinations');
assert.doesNotMatch(quietShell, /showReturnButton=!primaryDestinations\.has\(normalizedRoute\(current\)\)/, 'secondary routes must not be mistaken for their primary section');
assert.match(quietShell, /data-quiet-return/, 'secondary pages need the floating return control');
assert.match(quietShell, /history\.back\(\)/, 'the return control must perform exactly one history step');
assert.match(quietShell, /resetPageScroll\(\)/, 'route changes must reopen pages from the top');
assert.match(quietDesign, /\.quiet-return-button\{position:fixed;inset-inline-start:18px;bottom:calc\(max\(10px,env\(safe-area-inset-bottom\)\) \+ 76px\);[^}]*border-radius:50%;background:var\(--nav-cover\)/, 'the mobile return control must be circular, direction-aware, and above the bottom navigation');
assert.match(quietShell, /class="quiet-brand"/, 'the Dafatii logo must remain in the sidebar');
assert.doesNotMatch(quietShell, /quiet-toolbar-brand/, 'the main navigation header must not contain a website logo');
assert.doesNotMatch(quietDesign, /quiet-toolbar-brand/, 'retired top-bar logo styling must stay removed');
assert.doesNotMatch(quietDesign, /\.quiet-tabs/, 'the inherited bottom navigation implementation must be removed');
assert.match(quietShell, /const bottomNavItem =/, 'the bottom navigation must use dedicated markup');
assert.match(quietShell, /class="bottom-nav-item/, 'the bottom navigation must not reuse sidebar links');
assert.match(quietDesign, /\.quiet-toolbar\{position:fixed;top:10px;[^}]*border-radius:20px/, 'desktop main navigation must use a rounded fixed surface');
assert.match(quietDesign, /\.bottom-nav\{position:fixed;left:50%;[^}]*width:min\(calc\(100% - 24px\),440px\);height:64px/, 'authenticated mobile navigation must use the replacement floating dock');
assert.match(quietDesign, /@keyframes bottom-nav-arrive/, 'the replacement bottom navigation needs deliberate selection motion');
assert.match(quietShell, /const gelNavigationSelector = '\.landing-nav-tabs,\.quiet-desktop-tabs,\.bottom-nav,\.sub-inner'/, 'landing, pre-dafaa, and dafaa navigation must share one gel controller');
assert.match(quietShell, /function positionNavigationGel\(navigation, immediate=false\)/, 'the active gel must move to the current destination');
assert.match(quietShell, /navigation\.style\.setProperty\('--nav-count'/, 'signed-in navigation must adapt to dafaa and no-dafaa destination counts');
assert.match(quietDesign, /\.gel-nav>\.nav-gel\{[^}]*border:0;[^}]*background:color-mix\(in srgb,var\(--accent\) 16%,transparent\);[^}]*backdrop-filter:none;[^}]*box-shadow:none/, 'the selected indicator must be a flat semitransparent color with no glass or gel treatment');
assert.match(quietDesign, /\.gel-nav-ready>\.nav-gel\{[^}]*transition:transform \.42s cubic-bezier\(\.22,1,\.36,1\)/, 'the active indicator must slide between destinations');
assert.match(quietDesign, /\.quiet-desktop-tabs\{[^}]*background:var\(--nav-cover\)[^}]*border-radius:28px/, 'signed-in desktop navigation must use the shared semitransparent material');
assert.match(quietDesign, /\.landing-nav-tabs\{[^}]*background:var\(--nav-cover\)[^}]*border-radius:28px/, 'landing navigation must use the shared semitransparent material');
assert.match(quietDesign, /\.landing-nav-link span\{position:absolute;width:1px;height:1px;overflow:hidden;clip-path:inset\(50%\)/, 'landing navigation labels must remain accessible but visually icon-only');
assert.doesNotMatch(quietDesign, /landing-nav-link span\{display:block\}/, 'device overrides must not restore landing navigation labels');
assert.doesNotMatch(quietDesign, /\.bottom-nav-item\.is-active\{color:#fff\}/, 'the previous opaque active navigation treatment must be removed');
assert.match(quietDesign, /--nav-cover:rgba\(255,255,255,\.68\)/, 'light mode navigation cover must be translucent white');
assert.match(quietDesign, /html\[data-theme=dark\]\{[^}]*--nav-cover:rgba\(8,8,10,\.72\)/, 'dark mode navigation cover must be translucent near-black');
assert.match(quietDesign, /\.gel-nav>\.nav-gel\{[^}]*border-radius:24px/, 'the moving selected layer must retain the rounded shape');
assert.match(quietDesign, /\.gel-nav>\.landing-nav-link:not\(\.active\):hover,[^}]*background:transparent;color:var\(--text\)/, 'main and sub-navigation hover states must remain unfilled');
assert.match(quietDesign, /\.gel-nav>\.bottom-nav-item:not\(\.is-active\):hover \.bottom-nav-icon\{background:transparent\}/, 'bottom navigation hover must not create a filled surface');
assert.doesNotMatch(quietDesign, /--nav-hover/, 'the retired hover fill material must remain removed');
assert.match(quietDesign, /\.bottom-nav-item\.is-active \.bottom-nav-icon/, 'the active state must be scoped to the replacement component');
assert.match(quietDesign, /body \.quiet-workspace>\.sub-nav\{position:relative!important;top:auto!important;[^}]*margin:82px auto 0!important;[^}]*width:min\(720px,calc\(100% - 264px\)\)!important/, 'desktop and tablet sub-navigation must remain at the top of the page flow');
assert.match(quietDesign, /body \.quiet-workspace>\.sub-nav\{margin:72px auto 0!important;position:relative!important;top:auto!important;[^}]*width:min\(640px,calc\(100% - 20px\)\)!important/, 'mobile sub-navigation must scroll away with the page');
assert.doesNotMatch(quietDesign, /\.sub-nav \+ \.workspace-main/, 'flow-positioned sub-navigation must not leave fixed-bar compensation space');
assert.match(quietDesign, /body \.quiet-workspace \.sub-inner\{[^}]*justify-content:flex-start;direction:inherit/, 'sub-navigation must begin at the logical language edge');
assert.match(quietDesign, /body \.quiet-workspace \.sub-inner\{[^}]*background:var\(--nav-cover\)!important;[^}]*border-radius:28px/, 'sub-navigation must use the shared theme-aware translucent cover');
assert.match(quietDesign, /body \.quiet-workspace>\.sub-nav\{[^}]*background:transparent!important;[^}]*border:0;[^}]*box-shadow:none!important/, 'the previous outer sub-navigation card layer must be removed');
assert.match(quietDesign, /\.gel-nav>\.sub-link\.active\{background:transparent;color:var\(--accent\)/, 'sub-navigation selection must use the moving semitransparent layer instead of an opaque active tab');
assert.doesNotMatch(quietDesign, />\.workspace-main,body \.quiet-workspace>\.sub-nav\{[^}]*margin-inline-start/, 'sub-navigation must not inherit the sidebar content offset');
assert.match(quietDesign, /\.quiet-toolbar\{position:fixed;top:10px;/, 'desktop main navigation must be fixed to the viewport');
assert.match(quietDesign, /\.quiet-toolbar\{position:fixed;top:8px;inset-inline:10px;/, 'mobile main navigation must be fixed to the viewport');
assert.match(quietDesign, /\.bottom-nav-item:not\(\.is-active\):hover \.bottom-nav-icon/, 'replacement navigation icons need an interactive hover state');
const iconSystem = fs.readFileSync('icon-system.js', 'utf8');
for (const icon of ['nav-home','nav-library','nav-calendar','nav-community','nav-messages']) assert.match(iconSystem, new RegExp(`['"]${icon}['"]`), `${icon} must exist`);
assert.match(quietShell, /const mainNavIcons = Object\.freeze\(\{dashboard:'nav-home',subjects:'nav-library',calendar:'nav-calendar','study-rooms':'nav-community',chat:'nav-messages'\}\)/, 'all authenticated dafaa navigation surfaces must use the replacement icon family');
assert.match(iconSystem, /'nav-library':'M6 3\.5h12A2\.5/, 'the replacement library icon must be loaded');
assert.match(iconSystem, /'nav-calendar':'M6 4\.5h12A2\.5/, 'the replacement calendar icon must be loaded');
assert.doesNotMatch(iconSystem, /'nav-home':'M4\.5 10\.5 12 4l7\.5 6\.5/, 'the previous authenticated home icon must be removed');
assert.match(quietShell, /data-quiet-language/, 'the active shell needs an in-place language switch');
assert.match(quietShell, /applyInterfaceLanguage\(next\)/, 'language switching must use the canonical language preference');
assert.match(quietShell, /data-quiet-dafat/, 'the dafaa access button must open a dafaa popover');
assert.match(quietShell, /quiet-profile-popover/, 'the profile button must open a profile summary');
const app = fs.readFileSync('app.js', 'utf8');
assert.doesNotMatch(app, /subject-back|data-subjects-back/, 'return controls must not remain embedded in sub-navigation');
assert.doesNotMatch(app, /authOffline \? 'disabled'/, 'a failed startup check must not disable authentication');
assert.match(app, /dataset\.submitting/, 'authentication errors must survive availability events');
assert.match(app, /PRE_DAFAA_ROUTES/, 'users without an active dafaa need the limited navigation shell');
assert.match(app, /pending','payment_pending/, 'pending enrollments must remain outside the full dafaa workspace');
assert.match(app, /readString\('dafatii:interface-language'\)==='en'\?'en':'ar'/, 'Arabic must be the default interface language');
assert.match(app, /function applyInterfaceTheme\(theme=interfaceTheme\(\)\)/, 'the selected theme must have one canonical application path');
assert.match(app, /applyInterfaceLanguage\(button\.dataset\.interfaceLanguage\);render\(\)/, 'no-dafaa language switching must rebuild the consolidated shell');
assert.match(app, /querySelectorAll\('\[data-extra="dark-mode"\]'\).*applyInterfaceTheme/s, 'no-dafaa theme controls must apply and persist the selected theme');
assert.doesNotMatch(app, /applyInterfaceLanguage\(button\.dataset\.interfaceLanguage\);preDafaaWorkspace\(page\)/, 'language switching must not bypass the consolidated shell');
assert.match(app, /data-landing-section="home"[^>]*aria-label[^>]*>\$\{icon\('nav-home'\)\}/, 'landing navigation must use the shared icon family with accessible labels');
assert.match(app, /data-landing-section="about"/, 'the landing navigation must expose About us');
assert.match(app, /data-landing-section="contact"/, 'the landing navigation must expose Contact us');
assert.doesNotMatch(app, /Swipe right for edit or left for delete/, 'subject and lecture pages must not show swipe instructions');
const calendarUi = fs.readFileSync('calendar.js', 'utf8');
const calendarCss = fs.readFileSync('calendar.css', 'utf8');
assert.doesNotMatch(calendarUi, /calendar-toolbar|repeatLabel|Tap a row\/column header to edit/, 'calendar metadata badges must be removed from markup and code');
assert.doesNotMatch(calendarCss, /calendar-toolbar/, 'retired calendar metadata badge styles must be removed');
const rolePanels = fs.readFileSync('role-panels.js', 'utf8');
const rolePanelCss = fs.readFileSync('role-panels.css', 'utf8');
assert.match(rolePanels, /className='representer-panel-entry'/, 'dashboard management access must use the redesigned component');
assert.match(rolePanels, /head\.insertAdjacentElement\('afterend',button\)/, 'the management entry must sit directly below the dashboard heading');
assert.doesNotMatch(rolePanels, /head\.append\(button\)/, 'the management entry must not be appended to the end of the dashboard');
assert.match(rolePanelCss, /\.representer-panel-entry\{[^}]*grid-template-columns:48px minmax\(0,1fr\) 38px;[^}]*border-radius:22px/, 'the management entry must use the compact icon-led rounded design');
console.log('static boundary tests passed');
