import { ApiError, logEvent } from './http.js';
import { hashPassword, newPasswordSalt, randomId, randomToken, sha256, timingSafeEqual } from './crypto.js';

const SESSION_COOKIE = '__Host-dafatii_session';
const SESSION_TTL_MS = 30 * 24 * 60 * 60 * 1000;
const PASSWORD_ITERATIONS = 600000;
function cookieValue(request, name) { for (const part of (request.headers.get('Cookie') || '').split(';')) { const [key,...rest]=part.trim().split('='); if(key===name)return rest.join('='); } return null; }
export function sessionCookie(token,maxAge=SESSION_TTL_MS/1000){return `${SESSION_COOKIE}=${token}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${Math.floor(maxAge)}`;}
export function clearSessionCookie(){return `${SESSION_COOKIE}=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0`;}
export async function requireUser(request,env){const token=cookieValue(request,SESSION_COOKIE);if(!token)throw new ApiError(401,'authentication_required','Authentication required.');const tokenHash=await sha256(token),now=Date.now();const row=await env.DB.prepare(`SELECT s.id session_id,s.expires_at,s.last_seen_at,u.id,u.email,u.display_name FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=?`).bind(tokenHash).first();if(!row||Number(row.expires_at)<=now){if(row)await env.DB.prepare('DELETE FROM sessions WHERE id=?').bind(row.session_id).run();throw new ApiError(401,'invalid_session','Session is invalid or expired.');}if(now-Number(row.last_seen_at||0)>15*60*1000)await env.DB.prepare('UPDATE sessions SET last_seen_at=? WHERE id=?').bind(now,row.session_id).run();return{id:row.id,email:row.email,displayName:row.display_name,sessionId:row.session_id};}
async function abuseCheck(env,key){const now=Date.now(),windowMs=15*60*1000,max=12,bucket=await sha256(`login:${key}`);const row=await env.DB.prepare('SELECT window_started_at,attempts FROM login_attempts WHERE bucket=?').bind(bucket).first();if(!row||now-Number(row.window_started_at)>=windowMs){await env.DB.prepare('INSERT INTO login_attempts(bucket,window_started_at,attempts) VALUES(?,?,1) ON CONFLICT(bucket) DO UPDATE SET window_started_at=excluded.window_started_at,attempts=1').bind(bucket,now).run();return;}if(Number(row.attempts)>=max)throw new ApiError(429,'rate_limited','Too many attempts. Try again later.');await env.DB.prepare('UPDATE login_attempts SET attempts=attempts+1 WHERE bucket=?').bind(bucket).run();}
export async function signup(request,env,body){const email=String(body.email||'').trim().toLowerCase(),displayName=String(body.name||'').trim().slice(0,120),password=String(body.password||'');await abuseCheck(env,`${email}:${request.headers.get('CF-Connecting-IP')||'unknown'}`);if(!/^\S+@\S+\.\S+$/.test(email)||!displayName||password.length<10||password.length>256)throw new ApiError(400,'invalid_signup','Invalid account details. Password must be at least 10 characters.');if(await env.DB.prepare('SELECT 1 FROM users WHERE email=?').bind(email).first())throw new ApiError(400,'invalid_signup','Unable to create account with those details.');const salt=newPasswordSalt(),passwordHash=await hashPassword(password,salt,PASSWORD_ITERATIONS),userId=randomId('usr'),now=Date.now();await env.DB.prepare('INSERT INTO users(id,email,display_name,password_hash,password_salt,password_iterations,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').bind(userId,email,displayName,passwordHash,salt,PASSWORD_ITERATIONS,now,now).run();return createSession(env,userId);}
export async function login(request,env,body){const email=String(body.email||'').trim().toLowerCase(),password=String(body.password||'');await abuseCheck(env,`${email}:${request.headers.get('CF-Connecting-IP')||'unknown'}`);const row=await env.DB.prepare('SELECT * FROM users WHERE email=?').bind(email).first(),salt=row?.password_salt||newPasswordSalt(),iterations=Number(row?.password_iterations||PASSWORD_ITERATIONS),candidate=await hashPassword(password,salt,iterations);if(!row||!timingSafeEqual(candidate,row.password_hash)){logEvent('auth_failure',{reason:'invalid_credentials'});throw new ApiError(401,'invalid_credentials','Invalid email or password.');}return createSession(env,row.id);}
async function createSession(env,userId){const token=randomToken(32),tokenHash=await sha256(token),now=Date.now();await env.DB.prepare('INSERT INTO sessions(id,user_id,token_hash,created_at,expires_at,last_seen_at) VALUES(?,?,?,?,?,?)').bind(randomId('ses'),userId,tokenHash,now,now+SESSION_TTL_MS,now).run();return{token,expiresAt:now+SESSION_TTL_MS};}
export async function logout(request,env){const token=cookieValue(request,SESSION_COOKIE);if(token)await env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await sha256(token)).run();}
